(function () {
  'use strict';
  const categories = ['WORLD','BUILDINGS','PROPS','TERRAIN','NPC','AI','VEHICLES','GAME SYSTEMS','FUNCTIONS','AUDIO','EFFECTS','SCRIPTS','INTERACTIVE','UTILITIES'];
  const icons = { WORLD:'🌐', BUILDINGS:'🏢', PROPS:'📦', TERRAIN:'⛰️', NPC:'🧑', AI:'🧠', VEHICLES:'🏎️', 'GAME SYSTEMS':'🎮', FUNCTIONS:'⚙️', AUDIO:'🔊', EFFECTS:'✨', SCRIPTS:'⌨️', INTERACTIVE:'🚪', UTILITIES:'🧰' };
  const roomStyles = [{ id:'loft', name:'Open Studio', label:'Flexible creative loft', color:'#ff5ba7', walls:'l' }, { id:'suite', name:'Connected Suite', label:'Three linked rooms', color:'#61e7ff', walls:'h' }, { id:'courtyard', name:'Garden Courtyard', label:'Indoor / outdoor flow', color:'#b5ff55', walls:'u' }];
  const builderModels = [['canopy-tree','Canopy Tree','landscape'],['pine-tree','Pine Tree','landscape'],['flower-bed','Flower Bed','landscape'],['hedge-corner','Hedge Corner','landscape'],['garden-rocks','Garden Rocks','landscape'],['pond','Reflecting Pond','landscape'],['path-tile','Path Tile','landscape'],['hill','Soft Hill','landscape'],['lamp-post','Lamp Post','landscape'],['planter','Tall Planter','landscape'],['sofa','Cloud Sofa','interior'],['armchair','Accent Chair','interior'],['coffee-table','Coffee Table','interior'],['bookshelf','Bookshelf','interior'],['floor-lamp','Floor Lamp','interior'],['room-divider','Room Divider','interior'],['kitchen-island','Kitchen Island','interior'],['spiral-stairs','Spiral Stairs','interior'],['archway','Archway','interior'],['art-wall','Art Wall','interior']];
  const $ = (selector) => document.querySelector(selector); let state = { permissions:{}, land:[], assets:[], listings:[], placements:[], csrf:'' };
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[character]);
  const status = (message, error = false) => { $('#builder-status').textContent = message; $('#builder-status').classList.toggle('error', error); };
  async function api(path, options = {}) {
    const headers = { Accept:'application/json', ...(options.body ? { 'Content-Type':'application/json' } : {}), ...(state.csrf ? { 'X-CSRF-Token':state.csrf } : {}), ...(options.headers || {}) };
    const response = await window.MUZIKAZ_API.fetch(path, { ...options, headers, retries:0 }); const payload = await response.json().catch(() => ({}));
    if (!response.ok || payload.success === false) throw new Error(payload.message || 'Builder service request failed.'); return payload.data;
  }
  function card(asset, body, actions = '') {
    const functional = asset.function_data || asset.interaction_data || asset.ai_profile;
    return `<article class="builder-card"><div class="builder-card__visual">${icons[asset.builder_category] || '🧱'}</div><small>${escapeHtml(asset.builder_category)} · v${escapeHtml(asset.version)}</small><h3>${escapeHtml(asset.name)}</h3><p>${escapeHtml(asset.description || 'Reusable MUZIKAZ builder component.')}</p>${functional ? '<div class="builder-card__meta"><span>CONFIGURABLE FUNCTION</span></div>' : ''}${body}<div class="builder-actions">${actions}</div></article>`;
  }
  const button = (label, action, id, allowed = true) => allowed ? `<button type="button" data-action="${action}" data-id="${escapeHtml(id)}">${label}</button>` : '';
  function renderBuilderPack(filter = 'all') {
    $('#room-style-grid').innerHTML = roomStyles.map((room) => `<button type="button" class="room-style" data-room-style="${room.id}" style="--room-color:${room.color}"><span class="room-style__plan room-style__plan--${room.walls}" aria-hidden="true"><i></i><b></b></span><strong>${room.name}</strong><small>${room.label}</small></button>`).join('');
    $('#builder-model-grid').innerHTML = builderModels.filter(([, , type]) => filter === 'all' || type === filter).map(([id, name, type], index) => `<button type="button" class="builder-model" data-builder-model="${id}" data-model-name="${name}"><span class="builder-model__number">${String(index + 1).padStart(2, '0')}</span><img src="public/images/builder-pack/${id}.svg" alt="" loading="lazy"><span><strong>${name}</strong><small>${type.toUpperCase()}</small></span><b aria-hidden="true">＋</b></button>`).join('');
  }
  function setPackStatus(message) { $('#builder-pack-status').textContent = message; }
  function render() {
    $('#builder-balance').textContent = `${Number(state.balance || 0).toLocaleString()} MZK`;
    $('#builder-listings').innerHTML = state.listings.length ? state.listings.map((listing) => card(listing.asset, `<strong class="builder-price">${listing.price_mzk.toLocaleString()} MZK</strong>`, button('BUY WITH MZK','buy',listing.listing_id,state.permissions['market.builder.buy']) + button('PREVIEW','preview',listing.asset_id))).join('') : '<p class="builder-empty">No active listings in this category yet.</p>';
    $('#builder-assets').innerHTML = state.assets.length ? state.assets.map((asset) => card(asset, `<div class="builder-card__meta"><span>${escapeHtml(asset.asset_type)}</span><span>OWNED</span></div>`, button('PLACE','place',asset.id,state.permissions['builder.asset.place']) + button('CONFIGURE','configure',asset.id,state.permissions['builder.asset.configure']) + button('PREVIEW','preview',asset.id) + button(asset.listing ? 'LISTED' : 'SELL / LIST','list',asset.id,state.permissions['market.builder.sell'] && !asset.listing))).join('') : '<p class="builder-empty">Your Builder Backpack is empty. Purchase or create a game-builder asset to start.</p>';
    $('#builder-worlds').innerHTML = state.land.length ? state.land.map((land) => `<article class="builder-card"><div class="builder-card__visual">🗺️</div><small>OWNED LAND</small><h3>${escapeHtml(land.name)}</h3><p>World ID: ${escapeHtml(land.worldId)}</p></article>`).join('') : '<p class="builder-empty">No authoritative land deed is attached to this account.</p>';
    $('#builder-placements').innerHTML = state.placements.length ? state.placements.map((placement) => { const asset = state.assets.find((item) => item.id === placement.asset_id) || { name:placement.asset_id, builder_category:'WORLD', version:placement.asset_version }; return card(asset, `<div class="builder-card__meta"><span>${escapeHtml(placement.world_id)}</span><span>${escapeHtml(placement.placement_id)}</span></div>`, button('CONFIGURE','configure-placement',placement.placement_id,state.permissions['builder.asset.configure']) + button('REMOVE FROM WORLD','remove-placement',placement.placement_id,state.permissions['builder.world.edit'])); }).join('') : '<p class="builder-empty">Nothing has been placed in your worlds.</p>';
  }
  async function refresh() {
    const [profile, backpack, listings] = await Promise.all([api('/api/builder/permissions'), api('/api/builder/backpack'), api(`/api/builder/market?category=${encodeURIComponent($('#builder-category').value)}`)]);
    Object.assign(state, { permissions:profile.permissions, land:profile.land, balance:profile.mzk_balance, assets:backpack.assets, placements:backpack.placements, listings }); $('#builder-account').textContent = profile.account_id; render(); status('Builder account verified. Prices, ownership and permissions are validated by MUZIKAZ servers.');
  }
  function openDialog(title, fields, submit) { $('#builder-dialog-title').textContent = title; $('#builder-form-fields').innerHTML = fields; $('#builder-dialog-status').textContent = ''; $('#builder-form').onsubmit = async (event) => { event.preventDefault(); $('#builder-dialog-submit').disabled = true; try { await submit(new FormData(event.currentTarget)); $('#builder-dialog').close(); await refresh(); } catch (error) { $('#builder-dialog-status').textContent = error.message; } finally { $('#builder-dialog-submit').disabled = false; } }; $('#builder-dialog').showModal(); }
  const json = (value) => { if (!String(value || '').trim()) return {}; try { return JSON.parse(value); } catch (_) { throw new Error('Configuration must be valid JSON.'); } };
  function createAsset() { openDialog('Create Builder Asset', `<label>Name<input name="name" maxlength="140" required></label><label>Asset type<input name="asset_type" value="interactive_prop" required></label><label>Category<select name="builder_category">${categories.map((category) => `<option>${category}</option>`).join('')}</select></label><label>Version<input name="version" value="1.0.0"></label><label class="wide">Description<textarea name="description" rows="3"></textarea></label><label class="wide">GLB URL (optional)<input name="glb_url" type="url"></label><label class="wide">Function data (JSON)<textarea name="function_data" rows="4" placeholder='{"type":"teleporter","destination":null}'></textarea></label>`, (form) => api('/api/builder/assets', { method:'POST', body:JSON.stringify({ name:form.get('name'), asset_type:form.get('asset_type'), builder_category:form.get('builder_category'), version:form.get('version'), description:form.get('description'), glb_url:form.get('glb_url'), function_data:json(form.get('function_data')) }) })); }
  function act(action, id) {
    const asset = state.assets.find((item) => item.id === id) || state.listings.find((item) => item.asset_id === id)?.asset;
    if (action === 'buy') return confirm('Purchase this asset using your authoritative MZK balance?') && api(`/api/builder/listings/${encodeURIComponent(id)}/purchase`, { method:'POST', body:JSON.stringify({ request_id:crypto.randomUUID() }) }).then(refresh);
    if (action === 'preview') return alert(`${asset.name}\n\n${asset.description || ''}\n\n${JSON.stringify(asset.function_data || asset.interaction_data || {}, null, 2)}`);
    if (action === 'list') return openDialog(`List ${asset.name}`, '<label>MZK price<input name="price" type="number" min="1" max="1000000" required></label><label class="wide">Listing description<textarea name="description"></textarea></label>', (form) => api('/api/builder/listings', { method:'POST', body:JSON.stringify({ asset_id:id, price_mzk:Number(form.get('price')), description:form.get('description') }) }));
    if (action === 'place') return openDialog(`Place ${asset.name}`, `<label>Owned world<select name="world">${state.land.map((land) => `<option value="${escapeHtml(land.worldId)}">${escapeHtml(land.name)}</option>`)}</select></label><label class="wide">Instance configuration (JSON)<textarea name="configuration">{}</textarea></label>`, (form) => api('/api/builder/placements', { method:'POST', body:JSON.stringify({ world_id:form.get('world'), asset_id:id, transform:{ position:[0,0,0], rotation:[0,0,0], scale:[1,1,1] }, configuration:json(form.get('configuration')) }) }));
    if (action === 'configure') return alert('Configuration is stored per placed instance. Place this asset in an owned world first.');
    if (action === 'configure-placement') { const placement = state.placements.find((item) => item.placement_id === id); return openDialog('Configure World Instance', `<label class="wide">Configuration (JSON)<textarea name="configuration" rows="8">${escapeHtml(JSON.stringify(placement.configuration || {}, null, 2))}</textarea></label>`, (form) => api(`/api/builder/placements/${encodeURIComponent(id)}`, { method:'PATCH', body:JSON.stringify({ configuration:json(form.get('configuration')) }) })); }
    if (action === 'remove-placement') return confirm('Remove this instance from the world?') && api(`/api/builder/placements/${encodeURIComponent(id)}`, { method:'DELETE' }).then(refresh);
  }
  document.addEventListener('click', (event) => { const tab = event.target.closest('[data-builder-tab]'); if (tab) { document.querySelectorAll('[data-builder-tab]').forEach((item) => item.classList.toggle('active', item === tab)); document.querySelectorAll('[data-builder-panel]').forEach((item) => item.classList.toggle('active', item.dataset.builderPanel === tab.dataset.builderTab)); } const action = event.target.closest('[data-action]'); if (action) Promise.resolve(act(action.dataset.action, action.dataset.id)).catch((error) => status(error.message, true)); });
  $('#builder-category').innerHTML += categories.map((category) => `<option>${category}</option>`).join('');
  const requestedCategory = new URLSearchParams(location.search).get('category');
  if (categories.includes(requestedCategory)) $('#builder-category').value = requestedCategory;
  $('#builder-category').addEventListener('change', () => refresh().catch((error) => status(error.message, true))); $('#open-create-asset').addEventListener('click', createAsset);
  renderBuilderPack();
  document.querySelectorAll('[data-pack-filter]').forEach((control) => control.addEventListener('click', () => { document.querySelectorAll('[data-pack-filter]').forEach((item) => item.classList.toggle('active', item === control)); renderBuilderPack(control.dataset.packFilter); setPackStatus(`${control.textContent.trim()} shapes shown.`); }));
  $('#room-style-grid').addEventListener('click', (event) => { const room = event.target.closest('[data-room-style]'); if (!room) return; location.href = `environment-builder.html?layout=${encodeURIComponent(room.dataset.roomStyle)}`; });
  $('#builder-model-grid').addEventListener('click', (event) => { const model = event.target.closest('[data-builder-model]'); if (!model) return; model.classList.toggle('selected'); setPackStatus(`${model.dataset.modelName} ${model.classList.contains('selected') ? 'added to' : 'removed from'} your build tray.`); });
  document.querySelector('[data-pack-template]').addEventListener('click', (event) => { location.href = `environment-builder.html?layout=${encodeURIComponent(event.currentTarget.dataset.packTemplate)}`; });
  const requestedTab = location.hash.slice(1); if (['market','backpack','worlds'].includes(requestedTab)) document.querySelector(`[data-builder-tab="${requestedTab}"]`)?.click();
  api('/api/account/bootstrap').then((bootstrap) => { state.csrf = bootstrap.csrfToken || ''; return refresh(); }).catch((error) => { status(`${error.message} Sign in through Members to use the Builder Market.`, true); $('#builder-account').textContent = 'Authentication required'; });
}());
