(function () {
  'use strict';
  const STORAGE_KEY = 'muzikaz.environmentBuilder.scenes.v1';
  const TRAY_KEY = 'muzikaz.builder.buildTray';
  const models = [['canopy-tree','Canopy Tree','landscape',100],['pine-tree','Pine Tree','landscape',90],['flower-bed','Flower Bed','landscape',75],['hedge-corner','Hedge Corner','landscape',105],['garden-rocks','Garden Rocks','landscape',80],['pond','Reflecting Pond','landscape',125],['path-tile','Path Tile','landscape',90],['hill','Soft Hill','landscape',135],['lamp-post','Lamp Post','landscape',62],['planter','Tall Planter','landscape',60],['sofa','Cloud Sofa','interior',100],['armchair','Accent Chair','interior',72],['coffee-table','Coffee Table','interior',70],['bookshelf','Bookshelf','interior',92],['floor-lamp','Floor Lamp','interior',58],['room-divider','Room Divider','interior',105],['kitchen-island','Kitchen Island','interior',110],['spiral-stairs','Spiral Stairs','interior',118],['archway','Archway','interior',100],['art-wall','Art Wall','interior',92]];
  const layouts = { 'grand-floor':'Grand Build Floor', loft:'Open Studio', suite:'Connected Suite', courtyard:'Garden Courtyard' };
  const MAP_METRES = 40;
  const assetUrl = (modelId) => `public/images/builder-pack/${modelId}.svg`;
  const toWorld = (percent) => Number((((Number(percent) / 100) - .5) * MAP_METRES).toFixed(2));
  const toPercent = (metres) => Math.max(2, Math.min(98, ((Number(metres) / MAP_METRES) + .5) * 100));
  function prepareScene(candidate) {
    const ready = candidate && typeof candidate === 'object' ? candidate : {};
    ready.id ||= 'active'; ready.name ||= 'Untitled environment'; ready.layout = layouts[ready.layout] ? ready.layout : 'grand-floor'; ready.objects = Array.isArray(ready.objects) ? ready.objects : [];
    ready.schemaVersion = 2; ready.coordinateSystem = 'right-handed-y-up'; ready.mapSize = { width:MAP_METRES, depth:MAP_METRES, units:'metres' };
    ready.objects.forEach((object) => { object.elevation = Math.max(0, Number(object.elevation) || 0); object.locked = Boolean(object.locked); object.assetType ||= 'svg'; object.assetUrl ||= assetUrl(object.modelId); object.sizeMeters ||= Number(((modelFor(object.modelId)?.[3] || 100) / 50).toFixed(2)); });
    return ready;
  }
  const $ = (selector) => document.querySelector(selector);
  let scene = { id:'active', name:'Untitled environment', layout:'grand-floor', objects:[] }; let selectedId = null; let drag = null; let toastTimer;
  const modelFor = (id) => models.find((model) => model[0] === id);
  const uid = () => crypto.randomUUID?.() || `object-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  function readSaved() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null'); } catch (_) { return null; } }
  function persist(message = 'Progress saved locally') { prepareScene(scene); scene.objects.forEach((object) => { object.transform = { position:[toWorld(object.x), object.elevation, toWorld(object.y)], rotation:[0, Number(object.rotation) || 0, 0], scale:[object.scale, object.scale, object.scale] }; }); localStorage.setItem(STORAGE_KEY, JSON.stringify(scene)); $('#save-state').textContent = `Saved ${new Date().toLocaleTimeString([], { hour:'2-digit', minute:'2-digit' })}`; showToast(message); }
  function readTray() { try { const tray=JSON.parse(localStorage.getItem(TRAY_KEY)||'[]'); return Array.isArray(tray) ? tray : []; } catch (_) { return []; } }
  function importBuildTray() { if (scene.objects.length) return; const selected=readTray().filter((item)=>modelFor(item.id)); selected.forEach((item,index)=>scene.objects.push({ id:uid(), modelId:item.id, x:20+(index%5)*15, y:24+Math.floor(index/5)*18, rotation:0, scale:1, elevation:0, locked:false, assetType:'svg', assetUrl:assetUrl(item.id), sizeMeters:Number((modelFor(item.id)[3]/50).toFixed(2)) })); if (selected.length) showToast(`${selected.length} selected Builder Map item${selected.length===1?'':'s'} ready to place`); }
  function showToast(message) { const toast = $('#builder-toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 2200); }
  function renderLibrary(filter = 'all') { const shown = models.filter(([, , type]) => filter === 'all' || type === filter); $('#library-count').textContent = shown.length; $('#library-grid').innerHTML = shown.map(([id,name,type]) => `<button type="button" class="library-item" draggable="true" data-model="${id}"><img src="public/images/builder-pack/${id}.svg" alt=""><span><strong>${name}</strong><small>${type === 'landscape' ? 'OUTDOOR' : 'INTERIOR'}</small></span><b aria-hidden="true">＋</b></button>`).join(''); }
  function addObject(modelId, x = 50, y = 50) { const model = modelFor(modelId); if (!model) return; const offset = scene.objects.length % 5 * 2; const object = { id:uid(), modelId, x:Math.min(92, x + offset), y:Math.min(92, y + offset), rotation:0, scale:1, elevation:0, locked:false, assetType:'svg', assetUrl:assetUrl(modelId), sizeMeters:Number((model[3]/50).toFixed(2)) }; scene.objects.push(object); selectedId = object.id; renderScene(); showToast(`${model[1]} placed — drag it into position`); }
  function selected() { return scene.objects.find((object) => object.id === selectedId); }
  function renderScene() {
    const canvas = $('#land-canvas'); canvas.querySelectorAll('.land-object').forEach((element) => element.remove());
    for (const object of scene.objects) { const model = modelFor(object.modelId); if (!model) continue; const element = document.createElement('div'); element.className = `land-object${object.id === selectedId ? ' selected' : ''}${object.locked ? ' locked' : ''}`; element.dataset.objectId = object.id; element.style.cssText = `left:${object.x}%;top:${object.y}%;--rotation:${object.rotation}deg;--scale:${object.scale};--base-size:${model[3]}px`; element.setAttribute('role','button'); element.setAttribute('aria-label', `${model[1]}, placed object`); element.innerHTML = `<img src="public/images/builder-pack/${object.modelId}.svg" alt=""><span class="resize-handle" aria-hidden="true"></span>`; canvas.append(element); }
    $('#land-empty').hidden = scene.objects.length > 0; $('#object-count').textContent = `${scene.objects.length} OBJECT${scene.objects.length === 1 ? '' : 'S'} PLACED`; $('#scene-list-count').textContent = scene.objects.length;
    $('#scene-list').innerHTML = scene.objects.map((object) => { const model = modelFor(object.modelId); return `<button type="button" data-select-object="${object.id}"${object.id === selectedId ? ' aria-current="true"' : ''}><img src="public/images/builder-pack/${object.modelId}.svg" alt=""><span>${model[1]}</span></button>`; }).join(''); renderInspector();
  }
  function renderInspector() { const object = selected(), model = object && modelFor(object.modelId); $('#inspector-empty').hidden = Boolean(object); $('#inspector-controls').hidden = !object; if (!object) return; $('#selected-image').src = `public/images/builder-pack/${object.modelId}.svg`; $('#selected-name').textContent = model[1]; $('#selected-type').textContent = model[2].toUpperCase(); $('#rotation-control').value = object.rotation; $('#rotation-output').textContent = `${Math.round(object.rotation)}°`; $('#scale-control').value = Math.round(object.scale * 100); $('#scale-output').textContent = `${Math.round(object.scale * 100)}%`; $('#position-x').value = toWorld(object.x).toFixed(1); $('#position-y').value = object.elevation.toFixed(1); $('#position-z').value = toWorld(object.y).toFixed(1); const lock=$('#placement-lock-state'), button=$('#lock-object'); lock.classList.toggle('is-locked',object.locked); lock.querySelector('span').textContent=object.locked?'\uD83D\uDD12':'\uD83D\uDD13'; lock.querySelector('strong').textContent=object.locked?'PLACEMENT LOCKED':'PLACEMENT EDITABLE'; lock.querySelector('small').textContent=object.locked?'Unlock this item before moving, scaling or removing it.':'Lock the item when its 3D position is final.'; button.textContent=object.locked?'UNLOCK ITEM':'LOCK ITEM'; button.setAttribute('aria-pressed',String(object.locked)); }
  function updateLayout(layout) { scene.layout = layouts[layout] ? layout : 'grand-floor'; const canvas = $('#land-canvas'); canvas.className = `land-canvas layout-${scene.layout}`; canvas.setAttribute('aria-label', `${layouts[scene.layout]}. Drop objects here and use arrow keys to move the selected object.`); $('#layout-select').value = scene.layout; $('#layout-label').textContent = layouts[scene.layout].toUpperCase(); }
  function pointOnCanvas(event) { const rect = $('#land-canvas').getBoundingClientRect(); return { x:Math.max(2,Math.min(98,(event.clientX-rect.left)/rect.width*100)), y:Math.max(2,Math.min(98,(event.clientY-rect.top)/rect.height*100)) }; }
  function changeSelected(key, value) { const object = selected(); if (!object) return; if (object.locked) { showToast('Unlock this item before editing it'); renderInspector(); return; } object[key] = value; $('#save-state').textContent = 'Unsaved changes'; renderScene(); }
  renderLibrary();
  document.addEventListener('click', (event) => { const library = event.target.closest('[data-model]'); if (library) addObject(library.dataset.model); const listed = event.target.closest('[data-select-object]'); if (listed) { selectedId = listed.dataset.selectObject; renderScene(); } const placed = event.target.closest('.land-object'); if (placed && !drag) { selectedId = placed.dataset.objectId; renderScene(); } });
  document.addEventListener('dragstart', (event) => { const item = event.target.closest('[data-model]'); if (item) event.dataTransfer.setData('text/plain', item.dataset.model); });
  $('#land-canvas').addEventListener('dragover', (event) => event.preventDefault()); $('#land-canvas').addEventListener('drop', (event) => { event.preventDefault(); const point = pointOnCanvas(event); addObject(event.dataTransfer.getData('text/plain'), point.x, point.y); });
  $('#land-canvas').addEventListener('pointerdown', (event) => { const element = event.target.closest('.land-object'); if (!element) { selectedId = null; renderScene(); return; } event.preventDefault(); selectedId = element.dataset.objectId; document.querySelectorAll('.land-object').forEach((item) => item.classList.toggle('selected', item === element)); const object = selected(); if (object.locked) { showToast('Item is locked — unlock it in Object controls'); renderInspector(); return; } const point = pointOnCanvas(event); drag = { id:object.id, resize:event.target.classList.contains('resize-handle'), start:point, origin:{ x:object.x, y:object.y, scale:object.scale } }; element.setPointerCapture(event.pointerId); renderInspector(); });
  $('#land-canvas').addEventListener('pointermove', (event) => { if (!drag) return; const object = selected(); if (!object) return; const point = pointOnCanvas(event); if (drag.resize) object.scale = Math.max(.4, Math.min(2.4, drag.origin.scale + (point.x-drag.start.x)/24)); else { object.x = Math.max(2, Math.min(98, drag.origin.x + point.x-drag.start.x)); object.y = Math.max(2, Math.min(98, drag.origin.y + point.y-drag.start.y)); } const element = document.querySelector(`[data-object-id="${object.id}"]`); element.style.left=`${object.x}%`; element.style.top=`${object.y}%`; element.style.setProperty('--scale',object.scale); renderInspector(); });
  const endDrag = () => { if (drag) { drag = null; $('#save-state').textContent = 'Unsaved changes'; renderScene(); } }; $('#land-canvas').addEventListener('pointerup', endDrag); $('#land-canvas').addEventListener('pointercancel', endDrag);
  document.querySelectorAll('[data-library-filter]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-library-filter]').forEach((item) => item.classList.toggle('active', item === button)); renderLibrary(button.dataset.libraryFilter); }));
  $('#rotation-control').addEventListener('input', (event) => changeSelected('rotation', Number(event.target.value))); $('#scale-control').addEventListener('input', (event) => changeSelected('scale', Number(event.target.value)/100));
  document.querySelectorAll('[data-rotate]').forEach((button) => button.addEventListener('click', () => { const object = selected(); if (object) changeSelected('rotation', (object.rotation + Number(button.dataset.rotate) + 360) % 360); }));
  $('#reset-scale').addEventListener('click', () => changeSelected('scale', 1)); $('#position-x').addEventListener('change', (event) => changeSelected('x', toPercent(event.target.value))); $('#position-y').addEventListener('change', (event) => changeSelected('elevation', Math.max(0,Math.min(20,Number(event.target.value))))); $('#position-z').addEventListener('change', (event) => changeSelected('y', toPercent(event.target.value)));
  $('#lock-object').addEventListener('click', () => { const object=selected(); if (!object) return; object.locked=!object.locked; drag=null; renderScene(); persist(`${modelFor(object.modelId)[1]} placement ${object.locked?'locked':'unlocked'}`); });
  $('#remove-object').addEventListener('click', () => { if (selected()?.locked) { showToast('Unlock this item before removing it'); return; } scene.objects = scene.objects.filter((object) => object.id !== selectedId); selectedId = null; renderScene(); showToast('Object removed'); }); $('#duplicate-object').addEventListener('click', () => { const object = selected(); if (object) { const copy = {...object,id:uid(),x:Math.min(95,object.x+4),y:Math.min(95,object.y+4),locked:false,transform:undefined}; scene.objects.push(copy); selectedId=copy.id; renderScene(); } });
  $('#layout-select').addEventListener('change', (event) => { updateLayout(event.target.value); $('#save-state').textContent = 'Unsaved changes'; }); $('#scene-name').addEventListener('input', (event) => { scene.name = event.target.value; $('#save-state').textContent = 'Unsaved changes'; }); $('#save-scene').addEventListener('click', () => persist(`“${scene.name || 'Untitled environment'}” saved with ${scene.objects.length} objects`));
  $('#play-scene').addEventListener('click', () => { scene.id = scene.id && scene.id !== 'active' ? scene.id : `builder-${uid()}`; scene.gameplay = { multiplayer:true, enemies:true, weapons:true, pickups:true }; persist(`Opening “${scene.name || 'Untitled environment'}” as a playable multiplayer map`); location.href = `model-explorer.html?environment=${encodeURIComponent(scene.id)}&autoplay=1`; });
  $('#clear-scene').addEventListener('click', () => { if (!scene.objects.length || confirm('Start a new map? Your saved scene will remain available until you save again.')) { scene = prepareScene({ id:`builder-${uid()}`, name:'Untitled environment', layout:$('#layout-select').value, objects:[] }); selectedId=null; $('#scene-name').value=scene.name; updateLayout(scene.layout); renderScene(); showToast('New map ready'); } });
  $('#land-canvas').addEventListener('keydown', (event) => { const object=selected(); if (!object) return; if (object.locked) { if (['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Delete','Backspace'].includes(event.key)) showToast('Item is locked'); return; } const moves={ArrowLeft:['x',-1],ArrowRight:['x',1],ArrowUp:['y',-1],ArrowDown:['y',1]}; if (moves[event.key]) { event.preventDefault(); const [key,amount]=moves[event.key]; object[key]=Math.max(2,Math.min(98,object[key]+amount)); renderScene(); } if ((event.key==='Delete'||event.key==='Backspace') && !event.target.matches('input')) $('#remove-object').click(); });
  const requested = new URLSearchParams(location.search).get('layout'); const saved = readSaved(); if (saved && !requested && Array.isArray(saved.objects)) scene = prepareScene(saved); else scene = prepareScene(scene); if (requested && layouts[requested]) scene.layout = requested; importBuildTray(); $('#scene-name').value = scene.name || 'Untitled environment'; updateLayout(scene.layout); renderScene();
}());
