import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/+esm';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/GLTFLoader.js';
import { clone as cloneSkeleton } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/utils/SkeletonUtils.js';
import { createBuilderModel, updateBuilderModels } from './public/js/builder-models-3d.js';

const STORAGE_KEY='muzikaz.environmentBuilder.scenes.v2', LEGACY_KEY='muzikaz.environmentBuilder.scenes.v1', TRAY_KEY='muzikaz.builder.buildTray', CUSTOM_KEY='muzikaz.environmentBuilder.customItems.v1';
const colors=['#b9ff38','#63eaff','#ff5ba7','#ffcc3d','#ff6847','#a78bfa','#f8fafc','#334155'];
const icons=['🧙','🧝','🥷','🤖','👾','🐺','🧟','🐉','🗝️','💎','🧪','📜','🚪','🏰','🔥','🌲'];
const builtins=[
  ['canopy-tree','Canopy Tree','landscape',100],['pine-tree','Pine Tree','landscape',90],['flower-bed','Flower Bed','landscape',75],['hedge-corner','Hedge Corner','landscape',105],['garden-rocks','Garden Rocks','landscape',80],['pond','Reflecting Pond','landscape',125],['path-tile','Path Tile','landscape',90],['hill','Soft Hill','landscape',135],['lamp-post','Lamp Post','landscape',62],['planter','Tall Planter','landscape',60],['sofa','Cloud Sofa','interior',100],['armchair','Accent Chair','interior',72],['coffee-table','Coffee Table','interior',70],['bookshelf','Bookshelf','interior',92],['floor-lamp','Floor Lamp','interior',58],['room-divider','Room Divider','interior',105],['kitchen-island','Kitchen Island','interior',110],['spiral-stairs','Spiral Stairs','interior',118],['archway','Archway','interior',100],['art-wall','Art Wall','interior',92]
].map(([id,name,type,size])=>({id,name,type,size,image:`public/images/builder-pack/${id}.svg`,behavior:'decor',procedural:true}));
const gameplayModels=[
 {id:'hero-spawn',name:'Hero Spawn',type:'avatar',size:68,image:'public/images/backpack/dax-avatar.svg',behavior:'talk',color:'#63eaff',modelUrl:'public/models/avatars/DAX.glb',targetHeight:1.8},
 {id:'scout-avatar',name:'AAPE Scout',type:'avatar',size:68,image:'public/images/backpack/aape-avatar.svg',behavior:'quest',color:'#ffcc3d',modelUrl:'public/models/avatars/AAPE.glb',targetHeight:1.8},
 {id:'wolf-guardian',name:'Volt Guardian',type:'avatar',size:74,image:'public/images/backpack/volt-wolf-armor.svg',behavior:'patrol',color:'#a78bfa',modelUrl:'public/models/avatars/VOLTWOLF.glb',targetHeight:1.9},
 {id:'rad-tox',name:'RAD-TOX Mutant',type:'enemy',size:76,icon:'🧟',behavior:'hostile',color:'#b9ff38',modelUrl:'public/models/avatars/YUCKY_INMATE.glb',targetHeight:1.9},
 {id:'void-wolf',name:'Void Wolf',type:'enemy',size:72,icon:'🐺',behavior:'patrol',color:'#a78bfa',modelUrl:'public/models/avatars/wolfie.glb',targetHeight:1.2},
 {id:'ember-dragon',name:'Ember Dragon',type:'enemy',size:96,icon:'🐉',behavior:'hostile',color:'#ff6847',modelUrl:'public/models/avatars/SHARKO.glb',targetHeight:2.4},
 {id:'rogue-bot',name:'Rogue Bot',type:'enemy',size:70,icon:'🤖',behavior:'hostile',color:'#63eaff',modelUrl:'public/models/avatars/ROBOCOP.glb',targetHeight:1.85},
 {id:'quest-scroll',name:'Quest Scroll',type:'interactive',size:54,icon:'📜',behavior:'quest',color:'#ffcc3d'},
 {id:'treasure-crystal',name:'Energy Crystal',type:'interactive',size:55,icon:'💎',behavior:'pickup',color:'#63eaff'},
 {id:'healing-potion',name:'Healing Potion',type:'interactive',size:48,icon:'🧪',behavior:'heal',color:'#ff5ba7'},
 {id:'portal-door',name:'Portal Door',type:'interactive',size:82,icon:'🚪',behavior:'door',color:'#a78bfa'},
 {id:'campfire',name:'Campfire',type:'interactive',size:62,icon:'🔥',behavior:'talk',color:'#ff6847'}
];
const layouts={'grand-floor':'Grand Build Floor',loft:'Open Studio',suite:'Connected Suite',courtyard:'Garden Courtyard'};
const $=s=>document.querySelector(s), escapeHtml=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const readJson=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}};
const uid=()=>crypto.randomUUID?.()||`object-${Date.now()}-${Math.random().toString(16).slice(2)}`;
let customModels=readJson(CUSTOM_KEY,[]), activeFilter='all', chosenIcon=icons[0], selectedId=null, pendingModelId=null, dragging=null, toastTimer, viewMode='build';
let sceneData={version:2,id:'active',name:'Untitled environment',layout:'grand-floor',objects:[]};
const models=()=>[...builtins,...gameplayModels,...customModels], modelFor=id=>models().find(m=>m.id===id), selected=()=>sceneData.objects.find(o=>o.id===selectedId);

const renderer=new THREE.WebGLRenderer({canvas:$('#scene-canvas'),antialias:true,alpha:false}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.05;
const world=new THREE.Scene(); world.background=new THREE.Color(0x0b1710); world.fog=new THREE.Fog(0x0b1710,34,70);
const camera=new THREE.PerspectiveCamera(48,1,.05,120); camera.position.set(19,19,19);
const controls=new OrbitControls(camera,renderer.domElement); controls.target.set(0,0,0); controls.enableDamping=true; controls.maxPolarAngle=Math.PI*.49; controls.minDistance=4; controls.maxDistance=55; controls.mouseButtons={LEFT:THREE.MOUSE.PAN,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};
world.add(new THREE.HemisphereLight(0xbfe6ff,0x27351f,1.8)); const sun=new THREE.DirectionalLight(0xfff2d1,3.2);sun.position.set(12,23,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=sun.shadow.camera.bottom=-25;sun.shadow.camera.right=sun.shadow.camera.top=25;world.add(sun);
const terrainGeometry=new THREE.PlaneGeometry(40,40,80,80); const pos=terrainGeometry.attributes.position;
const terrainHeight=(x,z)=>{const layout=sceneData.layout; if(layout==='grand-floor')return 0; const ripple=.28*Math.sin(x*.31)*Math.cos(z*.27); if(layout==='loft')return ripple; if(layout==='suite')return .16*Math.sin(x*.45)+.1*Math.cos(z*.35); return ripple+1.1*Math.exp(-(x*x+z*z)/85)};
function shapeTerrain(){for(let i=0;i<pos.count;i++){const x=pos.getX(i),y=pos.getY(i);pos.setZ(i,terrainHeight(x,-y))}pos.needsUpdate=true;terrainGeometry.computeVertexNormals();}
shapeTerrain(); const terrain=new THREE.Mesh(terrainGeometry,new THREE.MeshStandardMaterial({color:0x315b32,roughness:.95,metalness:0}));terrain.rotation.x=-Math.PI/2;terrain.receiveShadow=true;terrain.name='terrain';world.add(terrain);
const grid=new THREE.GridHelper(40,40,0x92c45c,0x426347);grid.position.y=.025;grid.material.transparent=true;grid.material.opacity=.25;world.add(grid);
const placedGroup=new THREE.Group();world.add(placedGroup); const raycaster=new THREE.Raycaster(), pointer=new THREE.Vector2(), loader=new GLTFLoader(), cache=new Map(), runtime=new Map();
let preview=null, clock=new THREE.Clock();

function showToast(message){const t=$('#builder-toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function markChanged(){$('#save-state').textContent='Unsaved changes'}
function visual(model,alt=''){return model.image?`<img src="${model.image}" alt="${escapeHtml(alt)}">`:`<span class="item-glyph" aria-hidden="true">${model.icon||'◆'}</span>`}
function renderLibrary(filter=activeFilter){activeFilter=filter;const shown=models().filter(m=>filter==='all'||m.type===filter);$('#library-count').textContent=shown.length;$('#library-grid').innerHTML=shown.map(m=>`<button type="button" class="library-item${pendingModelId===m.id?' pending':''}" draggable="true" data-model="${m.id}" style="--item-color:${m.color||'#b9ff38'}">${visual(m)}<span><strong>${escapeHtml(m.name)}</strong><small>${m.type.toUpperCase()} · 3D</small></span><b>＋</b>${m.custom?`<i class="delete-library-item" data-delete-model="${m.id}">×</i>`:''}</button>`).join('')}
function makeObject(modelId,x=0,z=0){const m=modelFor(modelId);return{id:uid(),modelId,position:{x,y:terrainHeight(x,z),z},rotation:{x:0,y:0,z:0},scale:{x:1,y:1,z:1},groundOffset:0,materialSettings:{accent:m.color||colors[0],useAccent:false},animationState:{enabled:true,clip:null,time:0},functionalSettings:{behavior:m.behavior||'decor',active:false}}}
function migrateObject(o){const m=modelFor(o.modelId);if(o.position)return{...o,groundOffset:Number(o.groundOffset)||0,rotation:{x:0,y:0,z:0,...o.rotation},scale:typeof o.scale==='number'?{x:o.scale,y:o.scale,z:o.scale}:{x:1,y:1,z:1,...o.scale},materialSettings:o.materialSettings||{accent:o.color||m?.color||colors[0],useAccent:false},animationState:o.animationState||{enabled:true,clip:null,time:0},functionalSettings:o.functionalSettings||{behavior:o.behavior||m?.behavior||'decor',active:false}};const x=(Number(o.x)-50)*.4,z=(Number(o.y)-50)*.4;return{...makeObject(o.modelId,x,z),id:o.id||uid(),rotation:{x:0,y:THREE.MathUtils.degToRad(Number(o.rotation)||0),z:0},scale:{x:Number(o.scale)||1,y:Number(o.scale)||1,z:Number(o.scale)||1},materialSettings:{accent:o.color||m?.color||colors[0],useAccent:false},functionalSettings:{behavior:o.behavior||m?.behavior||'decor',active:false}}}
function createFallback(model){const root=new THREE.Group(), mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.55,...extra});let body;
 if(model.id==='portal-door'){body=new THREE.Mesh(new THREE.BoxGeometry(1.5,2.5,.18),mat(0x6e43bd,{metalness:.35}));body.position.y=1.25;body.name='door';root.add(body);}
 else if(model.id==='campfire'){for(let i=0;i<6;i++){const log=new THREE.Mesh(new THREE.CylinderGeometry(.09,.09,1,8),mat(0x633719));log.rotation.z=Math.PI/2;log.rotation.y=i*Math.PI/3;log.position.y=.15;root.add(log)}body=new THREE.Mesh(new THREE.ConeGeometry(.42,1.15,12),mat(0xff6a16,{emissive:0xff2400,emissiveIntensity:1.7,transparent:true,opacity:.82}));body.position.y=.75;body.userData.effect=true;root.add(body);}
 else {const c=model.id==='treasure-crystal'?new THREE.OctahedronGeometry(.55):model.id==='healing-potion'?new THREE.CapsuleGeometry(.28,.55,6,12):model.id==='quest-scroll'?new THREE.CylinderGeometry(.12,.12,1.15,16):new THREE.CapsuleGeometry(.42,1.05,6,12);body=new THREE.Mesh(c,mat(model.color||0xb9ff38,{emissive:model.type==='interactive'?new THREE.Color(model.color||0xb9ff38):0x000000,emissiveIntensity:.25}));body.position.y=model.type==='interactive'?.65:1; if(model.id==='quest-scroll')body.rotation.z=Math.PI/2;root.add(body)}
 return root;}
function prepareRoot(root,model,clips=[]){root.traverse(n=>{delete n.userData.builderRoot;if(n.isMesh){n.castShadow=true;n.receiveShadow=true;if(n.material){const mats=Array.isArray(n.material)?n.material:[n.material];mats.forEach(mat=>{if(mat.map)mat.map.colorSpace=THREE.SRGBColorSpace;mat.transparent=Boolean(mat.transparent||mat.opacity<1);mat.needsUpdate=true})}}});const box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3());if(model.targetHeight&&size.y>0){const s=model.targetHeight/size.y;root.scale.setScalar(s);box.setFromObject(root)}const min=box.min;root.position.y-=min.y;root.userData.clips=clips;return root}
async function templateFor(model){if(cache.has(model.id))return cache.get(model.id);const promise=(async()=>{if(model.procedural)return prepareRoot(createBuilderModel(model.id),model);if(model.modelUrl){try{const gltf=await loader.loadAsync(model.modelUrl);return prepareRoot(gltf.scene,model,gltf.animations)}catch(error){console.warn(`Could not load ${model.modelUrl}`,error)}}return prepareRoot(createFallback(model),model)})();cache.set(model.id,promise);return promise}
function disposeRuntime(id){const rt=runtime.get(id);if(!rt)return;rt.mixer?.stopAllAction();rt.root.traverse(n=>{if(n.userData.effectTimer)clearInterval(n.userData.effectTimer)});rt.root.removeFromParent();runtime.delete(id)}
async function buildRuntime(object,isPreview=false){const model=modelFor(object.modelId);if(!model)return null;const template=await templateFor(model);if(!isPreview&&!sceneData.objects.some(o=>o.id===object.id))return null;const root=model.procedural?template.clone(true):cloneSkeleton(template);root.userData={...root.userData,objectId:object.id,isPlaced:!isPreview};const clips=template.userData.clips||[];let mixer=null;if(clips.length){mixer=new THREE.AnimationMixer(root);const clip=clips.find(c=>c.name===object.animationState?.clip)||clips[0];object.animationState.clip=clip.name;const action=mixer.clipAction(clip);action.play();action.paused=!object.animationState.enabled;if(object.animationState.time)mixer.setTime(object.animationState.time)}
 placedGroup.add(root);runtime.set(object.id,{root,mixer,clips,baseY:root.position.y});updateTransform(object);return root}
function groundAt(x,z){raycaster.set(new THREE.Vector3(x,30,z),new THREE.Vector3(0,-1,0));const hit=raycaster.intersectObject(terrain,false)[0];return hit?hit.point.y:terrainHeight(x,z)}
function updateTransform(o){const rt=runtime.get(o.id);if(!rt)return;o.position.y=groundAt(o.position.x,o.position.z)+o.groundOffset;rt.root.position.set(o.position.x,o.position.y,o.position.z);rt.root.rotation.set(o.rotation.x,o.rotation.y,o.rotation.z);rt.root.scale.set(o.scale.x,o.scale.y,o.scale.z);rt.root.traverse(n=>{if(n.isMesh){if(n.userData.originalEmissive===undefined&&n.material?.emissive)n.userData.originalEmissive=n.material.emissive.getHex();if(n.material?.emissive)n.material.emissive.setHex(o.id===selectedId?0x174a55:n.userData.originalEmissive||0)}})}
function rebuildAll(){for(const id of [...runtime.keys()])disposeRuntime(id);sceneData.objects.forEach(o=>buildRuntime(o));updateUi()}
function updateUi(){const o=selected(),m=o&&modelFor(o.modelId);$('#land-empty').hidden=sceneData.objects.length>0;$('#object-count').textContent=`${sceneData.objects.length} OBJECT${sceneData.objects.length===1?'':'S'} PLACED`;$('#scene-list-count').textContent=sceneData.objects.length;$('#scene-list').innerHTML=sceneData.objects.map(x=>{const mod=modelFor(x.modelId);return mod?`<button data-select-object="${x.id}"${x.id===selectedId?' aria-current="true"':''} style="--item-color:${x.materialSettings.accent}">${visual(mod)}<span>${escapeHtml(mod.name)}</span><small>${x.groundOffset?`+${x.groundOffset.toFixed(1)}m`:'grounded'}</small></button>`:''}).join('');$('#inspector-empty').hidden=Boolean(o);$('#inspector-controls').hidden=!o;if(!o||!m)return;$('#selected-image').hidden=!m.image;if(m.image)$('#selected-image').src=m.image;$('#selected-name').textContent=m.name;$('#selected-type').textContent=`${m.type.toUpperCase()} · 3D`;$('#rotation-control').value=THREE.MathUtils.radToDeg(o.rotation.y);$('#rotation-output').textContent=`${Math.round(THREE.MathUtils.radToDeg(o.rotation.y))}°`;$('#scale-control').value=Math.round(o.scale.x*100);$('#scale-output').textContent=`${Math.round(o.scale.x*100)}%`;$('#position-x').value=o.position.x.toFixed(1);$('#position-y').value=o.position.z.toFixed(1);$('#elevation-control').value=o.groundOffset;$('#elevation-output').textContent=`${o.groundOffset.toFixed(1)} m`;$('#object-color').value=o.materialSettings.accent;$('#object-behavior').value=o.functionalSettings.behavior;$('#animation-enabled').checked=o.animationState.enabled;$('#color-swatches').innerHTML=colors.map(c=>`<button type="button" data-color="${c}" style="--swatch:${c}" aria-label="Use ${c}"></button>`).join('');sceneData.objects.forEach(updateTransform)}
function persist(message='Progress saved locally'){sceneData.version=2;for(const o of sceneData.objects){const rt=runtime.get(o.id);if(rt?.mixer)o.animationState.time=rt.mixer.time}localStorage.setItem(STORAGE_KEY,JSON.stringify(sceneData));localStorage.setItem(LEGACY_KEY,JSON.stringify(sceneData));$('#save-state').textContent=`Saved ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;showToast(message)}
function screenRay(event){const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera)}
function terrainPoint(event){screenRay(event);return raycaster.intersectObject(terrain,false)[0]?.point||null}
async function beginPlacement(modelId){pendingModelId=modelId;renderLibrary();$('#view-help').textContent='Move over the terrain for a grounded preview · click to place · Esc to cancel';if(preview){preview.removeFromParent();preview=null}const model=modelFor(modelId),template=await templateFor(model);if(pendingModelId!==modelId)return;preview=model.procedural?template.clone(true):cloneSkeleton(template);preview.traverse(n=>{if(n.isMesh){n.material=n.material.clone();n.material.transparent=true;n.material.opacity=Math.min(n.material.opacity,.55);n.material.depthWrite=false}});world.add(preview)}
function placePending(point){if(!pendingModelId)return;const o=makeObject(pendingModelId,point.x,point.z);sceneData.objects.push(o);selectedId=o.id;const name=modelFor(o.modelId).name;pendingModelId=null;if(preview){preview.removeFromParent();preview=null}buildRuntime(o);markChanged();renderLibrary();updateUi();showToast(`${name} placed as a grounded 3D object`)}
function selectObject(id){selectedId=id;updateUi()}
function removeSelected(){if(!selectedId)return;disposeRuntime(selectedId);sceneData.objects=sceneData.objects.filter(o=>o.id!==selectedId);selectedId=null;markChanged();updateUi();showToast('Object and its animation were removed')}
function changeSelected(fn){const o=selected();if(!o)return;fn(o);updateTransform(o);markChanged();updateUi()}
function interact(o=selected()){if(!o)return;const rt=runtime.get(o.id);o.functionalSettings.active=!o.functionalSettings.active;const behavior=o.functionalSettings.behavior;rt?.root.traverse(n=>{if(behavior==='door'&&n.name==='door')n.rotation.y=o.functionalSettings.active?-Math.PI*.62:0;if(behavior==='pickup')n.visible=!o.functionalSettings.active;if(behavior==='hostile')n.rotation.x=o.functionalSettings.active?-.28:0;if((behavior==='talk'||behavior==='heal'||behavior==='quest')&&n.isMesh&&n.material?.emissive)n.material.emissiveIntensity=o.functionalSettings.active?1.4:.25});showToast(`${modelFor(o.modelId).name}: ${o.functionalSettings.active?'interaction active':'interaction reset'}`);markChanged()}

renderer.domElement.addEventListener('pointermove',e=>{const point=terrainPoint(e);if(preview&&point){preview.position.copy(point);const box=new THREE.Box3().setFromObject(preview);preview.position.y+=point.y-box.min.y}if(!dragging||!point)return;const o=selected();o.position.x=THREE.MathUtils.clamp(point.x,-19.5,19.5);o.position.z=THREE.MathUtils.clamp(point.z,-19.5,19.5);updateTransform(o);updateUi()});
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0||viewMode==='walkthrough')return;const point=terrainPoint(e);if(pendingModelId&&point){placePending(point);return}screenRay(e);const hit=raycaster.intersectObjects([...runtime.values()].map(r=>r.root),true).find(h=>h.object.userData.builderRoot||h.object.parent);let node=hit?.object;while(node&&!node.userData.objectId)node=node.parent;if(node?.userData.objectId){selectObject(node.userData.objectId);dragging={id:selectedId};controls.enabled=false}else{selectedId=null;updateUi()}});
addEventListener('pointerup',()=>{if(dragging){dragging=null;controls.enabled=true;markChanged()}});addEventListener('keydown',e=>{if(e.key==='Escape'&&pendingModelId){pendingModelId=null;preview?.removeFromParent();preview=null;renderLibrary()}if((e.key==='Delete'||e.key==='Backspace')&&!/INPUT|SELECT/.test(document.activeElement.tagName))removeSelected()});
document.addEventListener('click',e=>{const del=e.target.closest('[data-delete-model]');if(del){e.stopPropagation();customModels=customModels.filter(m=>m.id!==del.dataset.deleteModel);localStorage.setItem(CUSTOM_KEY,JSON.stringify(customModels));renderLibrary();return}const library=e.target.closest('[data-model]');if(library)beginPlacement(library.dataset.model);const listed=e.target.closest('[data-select-object]');if(listed)selectObject(listed.dataset.selectObject);const swatch=e.target.closest('[data-color]');if(swatch)changeSelected(o=>{o.materialSettings.accent=swatch.dataset.color;o.materialSettings.useAccent=true});const mode=e.target.closest('[data-view-mode]');if(mode){viewMode=mode.dataset.viewMode;document.querySelectorAll('[data-view-mode]').forEach(b=>b.classList.toggle('active',b===mode));controls.mouseButtons=viewMode==='walkthrough'?{LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN}:{LEFT:THREE.MOUSE.PAN,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};$('#view-help').textContent=viewMode==='walkthrough'?'Drag to orbit · right-drag to pan · wheel to move through the scene':'Select an item, then click the terrain to place it'}});
document.addEventListener('dragstart',e=>{const item=e.target.closest('[data-model]');if(item)e.dataTransfer.setData('text/plain',item.dataset.model)});renderer.domElement.addEventListener('dragover',e=>e.preventDefault());renderer.domElement.addEventListener('drop',e=>{e.preventDefault();pendingModelId=e.dataTransfer.getData('text/plain');const p=terrainPoint(e);if(p)placePending(p)});
document.querySelectorAll('[data-library-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-library-filter]').forEach(x=>x.classList.toggle('active',x===b));renderLibrary(b.dataset.libraryFilter)}));
$('#rotation-control').addEventListener('input',e=>changeSelected(o=>o.rotation.y=THREE.MathUtils.degToRad(+e.target.value)));document.querySelectorAll('[data-rotate]').forEach(b=>b.addEventListener('click',()=>changeSelected(o=>o.rotation.y+=THREE.MathUtils.degToRad(+b.dataset.rotate))));$('#scale-control').addEventListener('input',e=>changeSelected(o=>o.scale.set?o.scale.set(+e.target.value/100,+e.target.value/100,+e.target.value/100):o.scale={x:+e.target.value/100,y:+e.target.value/100,z:+e.target.value/100}));
$('#reset-scale').addEventListener('click',()=>changeSelected(o=>o.scale={x:1,y:1,z:1}));$('#position-x').addEventListener('change',e=>changeSelected(o=>o.position.x=THREE.MathUtils.clamp(+e.target.value,-20,20)));$('#position-y').addEventListener('change',e=>changeSelected(o=>o.position.z=THREE.MathUtils.clamp(+e.target.value,-20,20)));$('#elevation-control').addEventListener('input',e=>changeSelected(o=>o.groundOffset=+e.target.value));$('#snap-ground').addEventListener('click',()=>changeSelected(o=>o.groundOffset=0));$('#object-color').addEventListener('input',e=>changeSelected(o=>{o.materialSettings.accent=e.target.value;o.materialSettings.useAccent=true}));$('#object-behavior').addEventListener('change',e=>changeSelected(o=>o.functionalSettings.behavior=e.target.value));$('#animation-enabled').addEventListener('change',e=>changeSelected(o=>{o.animationState.enabled=e.target.checked;const rt=runtime.get(o.id);rt?.mixer?._actions.forEach(a=>a.paused=!e.target.checked)}));$('#interact-object').addEventListener('click',()=>interact());
$('#remove-object').addEventListener('click',removeSelected);$('#duplicate-object').addEventListener('click',()=>{const o=selected();if(!o)return;const copy=structuredClone(o);copy.id=uid();copy.position.x=Math.min(19,copy.position.x+1);copy.position.z=Math.min(19,copy.position.z+1);sceneData.objects.push(copy);selectedId=copy.id;buildRuntime(copy);markChanged();updateUi()});
function updateLayout(layout){sceneData.layout=layouts[layout]?layout:'grand-floor';$('#layout-select').value=sceneData.layout;$('#layout-label').textContent=layouts[sceneData.layout].toUpperCase();shapeTerrain();sceneData.objects.forEach(updateTransform);markChanged()}
$('#layout-select').addEventListener('change',e=>updateLayout(e.target.value));$('#scene-name').addEventListener('input',e=>{sceneData.name=e.target.value;markChanged()});$('#save-scene').addEventListener('click',()=>persist(`“${sceneData.name}” saved with complete 3D state`));$('#play-scene').addEventListener('click',()=>{sceneData.gameplay={multiplayer:true, enemies:true, weapons:true, pickups:true, customRoles:true};persist('Scene saved — walkthrough enabled');document.querySelector('[data-view-mode="walkthrough"]').click()});$('#clear-scene').addEventListener('click',()=>{if(sceneData.objects.length&&!confirm('Start a new map?'))return;sceneData={version:2,id:uid(),name:'Untitled environment',layout:sceneData.layout,objects:[]};selectedId=null;$('#scene-name').value=sceneData.name;rebuildAll()});
// Saved scenes also remain compatible with the full game route:
// model-explorer.html?environment=<scene id>&autoplay=1
$('#icon-picker').innerHTML=icons.map((i,n)=>`<button type="button" data-icon="${i}"${n?'':' aria-current="true"'}>${i}</button>`).join('');function updateMakerPreview(){$('#maker-preview-icon').textContent=chosenIcon;$('#maker-preview-name').textContent=$('#custom-item-name').value||'Untitled item';$('#maker-preview').style.setProperty('--item-color',$('#custom-item-color').value)}$('#open-item-maker').addEventListener('click',()=>{updateMakerPreview();$('#item-maker').showModal()});$('#icon-picker').addEventListener('click',e=>{const b=e.target.closest('[data-icon]');if(!b)return;chosenIcon=b.dataset.icon;updateMakerPreview()});$('#custom-item-name').addEventListener('input',updateMakerPreview);$('#custom-item-color').addEventListener('input',updateMakerPreview);$('#item-maker-form').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const name=$('#custom-item-name').value.trim();if(!name)return;const model={id:`custom-${uid()}`,name,type:$('#custom-item-type').value,size:72,icon:chosenIcon,color:$('#custom-item-color').value,behavior:$('#custom-item-behavior').value,custom:true};customModels.push(model);localStorage.setItem(CUSTOM_KEY,JSON.stringify(customModels));renderLibrary();$('#item-maker').close();beginPlacement(model.id)});

const sideCanvas=$('#side-view-canvas'),side=sideCanvas.getContext('2d');function drawSideView(){const rect=sideCanvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(sideCanvas.width!==w||sideCanvas.height!==h){sideCanvas.width=w;sideCanvas.height=h}side.setTransform(dpr,0,0,dpr,0,0);const W=rect.width,H=rect.height;side.clearRect(0,0,W,H);side.fillStyle='#07100b';side.fillRect(0,0,W,H);side.beginPath();for(let px=0;px<=W;px++){const x=px/W*40-20,y=H-28-terrainHeight(x,0)*20;px?side.lineTo(px,y):side.moveTo(px,y)}side.lineTo(W,H);side.lineTo(0,H);side.fillStyle='#264c2d';side.fill();side.strokeStyle='#80ba5a';side.stroke();sceneData.objects.forEach(o=>{const x=(o.position.x+20)/40*W,ground=H-28-groundAt(o.position.x,o.position.z)*20,top=ground-o.groundOffset*20-18*o.scale.y;side.strokeStyle=o.groundOffset?'#ffcc3d':'#63eaff';side.lineWidth=3;side.beginPath();side.moveTo(x,ground);side.lineTo(x,top);side.stroke();side.fillStyle=o.id===selectedId?'#fff':o.materialSettings.accent;side.fillRect(x-4,top-4,8,8)})}
window.MuzikazEnvironmentBuilder={getScene:()=>structuredClone(sceneData),getObject3D:id=>runtime.get(id)?.root||null,snapToGround:id=>{const o=sceneData.objects.find(item=>item.id===id);if(o){o.groundOffset=0;updateTransform(o)}}};
function resize(){const rect=renderer.domElement.parentElement.getBoundingClientRect(),w=rect.width,h=rect.height;if(renderer.domElement.width!==Math.round(w*renderer.getPixelRatio())||renderer.domElement.height!==Math.round(h*renderer.getPixelRatio())){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}}
function animate(){requestAnimationFrame(animate);resize();const dt=Math.min(clock.getDelta(),.05),elapsed=clock.elapsedTime;controls.update();runtime.forEach((rt,id)=>{const o=sceneData.objects.find(x=>x.id===id);if(rt.mixer&&o?.animationState.enabled)rt.mixer.update(dt);rt.root.traverse(n=>{if(n.userData.effect){n.scale.y=1+Math.sin(elapsed*7)*.12;n.rotation.y=elapsed*.8}})});updateBuilderModels(placedGroup,elapsed);renderer.render(world,camera);drawSideView()}animate();

const requested=new URLSearchParams(location.search).get('layout'),saved=readJson(STORAGE_KEY,readJson(LEGACY_KEY,null));if(saved&&Array.isArray(saved.objects))sceneData={...sceneData,...saved,objects:saved.objects.filter(o=>modelFor(o.modelId)).map(migrateObject)};if(requested&&layouts[requested])sceneData.layout=requested;const tray=readJson(TRAY_KEY,[]);if(!sceneData.objects.length)tray.filter(i=>modelFor(i.id)).forEach((i,n)=>sceneData.objects.push(makeObject(i.id,-8+(n%5)*4,-5+Math.floor(n/5)*4)));$('#scene-name').value=sceneData.name;$('#layout-select').value=sceneData.layout;$('#layout-label').textContent=layouts[sceneData.layout].toUpperCase();shapeTerrain();renderLibrary();rebuildAll();
