(function () {
  'use strict';
  const STORAGE_KEY = 'muzikaz.environmentBuilder.scenes.v1';
  const TRAY_KEY = 'muzikaz.builder.buildTray';
  const CUSTOM_KEY = 'muzikaz.environmentBuilder.customItems.v1';
  const colors = ['#b9ff38','#63eaff','#ff5ba7','#ffcc3d','#ff6847','#a78bfa','#f8fafc','#334155'];
  const icons = ['🧙','🧝','🥷','🤖','👾','🐺','🧟','🐉','🗝️','💎','🧪','📜','🚪','🏰','🔥','🌲'];
  const builtins = [
    ['canopy-tree','Canopy Tree','landscape',100],['pine-tree','Pine Tree','landscape',90],['flower-bed','Flower Bed','landscape',75],['hedge-corner','Hedge Corner','landscape',105],['garden-rocks','Garden Rocks','landscape',80],['pond','Reflecting Pond','landscape',125],['path-tile','Path Tile','landscape',90],['hill','Soft Hill','landscape',135],['lamp-post','Lamp Post','landscape',62],['planter','Tall Planter','landscape',60],['sofa','Cloud Sofa','interior',100],['armchair','Accent Chair','interior',72],['coffee-table','Coffee Table','interior',70],['bookshelf','Bookshelf','interior',92],['floor-lamp','Floor Lamp','interior',58],['room-divider','Room Divider','interior',105],['kitchen-island','Kitchen Island','interior',110],['spiral-stairs','Spiral Stairs','interior',118],['archway','Archway','interior',100],['art-wall','Art Wall','interior',92]
  ].map(([id,name,type,size]) => ({ id,name,type,size,image:`public/images/builder-pack/${id}.svg`,behavior:'decor' }));
  const gameplayModels = [
    {id:'hero-spawn',name:'Hero Spawn',type:'avatar',size:68,image:'public/images/backpack/dax-avatar.svg',behavior:'talk',color:'#63eaff'},
    {id:'scout-avatar',name:'AAPE Scout',type:'avatar',size:68,image:'public/images/backpack/aape-avatar.svg',behavior:'quest',color:'#ffcc3d'},
    {id:'wolf-guardian',name:'Volt Guardian',type:'avatar',size:74,image:'public/images/backpack/volt-wolf-armor.svg',behavior:'patrol',color:'#a78bfa'},
    {id:'rad-tox',name:'RAD-TOX Mutant',type:'enemy',size:76,icon:'🧟',behavior:'hostile',color:'#b9ff38'},
    {id:'void-wolf',name:'Void Wolf',type:'enemy',size:72,icon:'🐺',behavior:'patrol',color:'#a78bfa'},
    {id:'ember-dragon',name:'Ember Dragon',type:'enemy',size:96,icon:'🐉',behavior:'hostile',color:'#ff6847'},
    {id:'rogue-bot',name:'Rogue Bot',type:'enemy',size:70,icon:'🤖',behavior:'hostile',color:'#63eaff'},
    {id:'quest-scroll',name:'Quest Scroll',type:'interactive',size:54,icon:'📜',behavior:'quest',color:'#ffcc3d'},
    {id:'treasure-crystal',name:'Energy Crystal',type:'interactive',size:55,icon:'💎',behavior:'pickup',color:'#63eaff'},
    {id:'healing-potion',name:'Healing Potion',type:'interactive',size:48,icon:'🧪',behavior:'heal',color:'#ff5ba7'},
    {id:'portal-door',name:'Portal Door',type:'interactive',size:82,icon:'🚪',behavior:'door',color:'#a78bfa'},
    {id:'campfire',name:'Campfire',type:'interactive',size:62,icon:'🔥',behavior:'talk',color:'#ff6847'}
  ];
  const layouts = { 'grand-floor':'Grand Build Floor', loft:'Open Studio', suite:'Connected Suite', courtyard:'Garden Courtyard' };
  const $ = (selector) => document.querySelector(selector);
  const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (character) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));
  let customModels = readJson(CUSTOM_KEY, []); let activeFilter = 'all'; let chosenIcon = icons[0];
  let scene = { id:'active', name:'Untitled environment', layout:'grand-floor', objects:[] }; let selectedId = null; let drag = null; let toastTimer;
  const models = () => [...builtins, ...gameplayModels, ...customModels];
  const modelFor = (id) => models().find((model) => model.id === id);
  const uid = () => crypto.randomUUID?.() || `object-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  function readJson(key, fallback) { try { return JSON.parse(localStorage.getItem(key) || 'null') || fallback; } catch (_) { return fallback; } }
  function persist(message = 'Progress saved locally') { localStorage.setItem(STORAGE_KEY, JSON.stringify(scene)); $('#save-state').textContent = `Saved ${new Date().toLocaleTimeString([], { hour:'2-digit', minute:'2-digit' })}`; showToast(message); }
  function markChanged() { $('#save-state').textContent = 'Unsaved changes'; }
  function importBuildTray() { if (scene.objects.length) return; const selected=readJson(TRAY_KEY, []).filter((item)=>modelFor(item.id)); selected.forEach((item,index)=>scene.objects.push(makeObject(item.id,20+(index%5)*15,24+Math.floor(index/5)*18))); }
  function showToast(message) { const toast = $('#builder-toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 2200); }
  function visual(model, alt = '') { return model.image ? `<img src="${model.image}" alt="${escapeHtml(alt)}">` : `<span class="item-glyph" aria-hidden="true">${model.icon || '◆'}</span>`; }
  function renderLibrary(filter = activeFilter) { activeFilter = filter; const shown = models().filter((model) => filter === 'all' || model.type === filter); $('#library-count').textContent = shown.length; $('#library-grid').innerHTML = shown.map((model) => `<button type="button" class="library-item" draggable="true" data-model="${model.id}" style="--item-color:${model.color || '#b9ff38'}">${visual(model)}<span><strong>${escapeHtml(model.name)}</strong><small>${model.type.toUpperCase()}</small></span><b aria-hidden="true">＋</b>${model.custom ? `<i class="delete-library-item" data-delete-model="${model.id}" title="Delete custom item" aria-label="Delete ${escapeHtml(model.name)}">×</i>` : ''}</button>`).join(''); }
  function makeObject(modelId,x=50,y=50) { const model=modelFor(modelId); return { id:uid(),modelId,x,y,rotation:0,scale:1,color:model.color||colors[0],behavior:model.behavior||'decor' }; }
  function addObject(modelId, x = 50, y = 50) { const model = modelFor(modelId); if (!model) return; const offset = scene.objects.length % 5 * 2; const object = makeObject(modelId,Math.min(92,x+offset),Math.min(92,y+offset)); scene.objects.push(object); selectedId = object.id; markChanged(); renderScene(); showToast(`${model.name} placed — drag it into position`); }
  function selected() { return scene.objects.find((object) => object.id === selectedId); }
  function renderScene() {
    const canvas = $('#land-canvas'); canvas.querySelectorAll('.land-object').forEach((element) => element.remove());
    for (const object of scene.objects) { const model = modelFor(object.modelId); if (!model) continue; const element = document.createElement('div'); element.className = `land-object type-${model.type}${object.id === selectedId ? ' selected' : ''}`; element.dataset.objectId = object.id; element.style.cssText = `left:${object.x}%;top:${object.y}%;--rotation:${object.rotation}deg;--scale:${object.scale};--base-size:${model.size}px;--item-color:${object.color||model.color||colors[0]}`; element.setAttribute('role','button'); element.setAttribute('aria-label', `${model.name}, ${model.type}, ${object.behavior || 'decor'}`); element.innerHTML = `<span class="object-visual">${visual(model)}</span><span class="behavior-marker">${model.type === 'enemy' ? '!' : model.type === 'avatar' ? '●' : '◆'}</span><span class="resize-handle" aria-hidden="true"></span>`; canvas.append(element); }
    $('#land-empty').hidden = scene.objects.length > 0; $('#object-count').textContent = `${scene.objects.length} OBJECT${scene.objects.length === 1 ? '' : 'S'} PLACED`; $('#scene-list-count').textContent = scene.objects.length;
    $('#scene-list').innerHTML = scene.objects.map((object) => { const model = modelFor(object.modelId); if (!model) return ''; return `<button type="button" data-select-object="${object.id}"${object.id === selectedId ? ' aria-current="true"' : ''} style="--item-color:${object.color}">${visual(model)}<span>${escapeHtml(model.name)}</span><small>${escapeHtml(object.behavior || 'decor')}</small></button>`; }).join(''); renderInspector();
  }
  function renderInspector() { const object = selected(), model = object && modelFor(object.modelId); $('#inspector-empty').hidden = Boolean(object); $('#inspector-controls').hidden = !object; if (!object || !model) return; $('#selected-image').hidden=!model.image; if(model.image) $('#selected-image').src=model.image; $('#selected-name').textContent = model.name; $('#selected-type').textContent = model.type.toUpperCase(); $('#rotation-control').value = object.rotation; $('#rotation-output').textContent = `${Math.round(object.rotation)}°`; $('#scale-control').value = Math.round(object.scale * 100); $('#scale-output').textContent = `${Math.round(object.scale * 100)}%`; $('#position-x').value = object.x.toFixed(1); $('#position-y').value = object.y.toFixed(1); $('#object-color').value = object.color || colors[0]; $('#object-behavior').value = object.behavior || 'decor'; $('#color-swatches').innerHTML=colors.map(color=>`<button type="button" data-color="${color}" style="--swatch:${color}" aria-label="Use ${color}"${color===object.color?' aria-current="true"':''}></button>`).join(''); }
  function updateLayout(layout) { scene.layout = layouts[layout] ? layout : 'grand-floor'; const canvas = $('#land-canvas'); canvas.className = `land-canvas layout-${scene.layout}`; canvas.setAttribute('aria-label', `${layouts[scene.layout]}. Drop objects here and use arrow keys to move the selected object.`); $('#layout-select').value = scene.layout; $('#layout-label').textContent = layouts[scene.layout].toUpperCase(); }
  function pointOnCanvas(event) { const rect = $('#land-canvas').getBoundingClientRect(); return { x:Math.max(2,Math.min(98,(event.clientX-rect.left)/rect.width*100)), y:Math.max(2,Math.min(98,(event.clientY-rect.top)/rect.height*100)) }; }
  function changeSelected(key, value) { const object = selected(); if (!object) return; object[key] = value; markChanged(); renderScene(); }
  renderLibrary();
  document.addEventListener('click', (event) => { const deletion=event.target.closest('[data-delete-model]'); if(deletion){ event.preventDefault(); event.stopPropagation(); const id=deletion.dataset.deleteModel; customModels=customModels.filter(model=>model.id!==id); scene.objects=scene.objects.filter(object=>object.modelId!==id); localStorage.setItem(CUSTOM_KEY,JSON.stringify(customModels)); if(!scene.objects.some(object=>object.id===selectedId)) selectedId=null; renderLibrary(); renderScene(); showToast('Custom item removed from library and map'); return; } const library = event.target.closest('[data-model]'); if (library) addObject(library.dataset.model); const listed = event.target.closest('[data-select-object]'); if (listed) { selectedId = listed.dataset.selectObject; renderScene(); } const placed = event.target.closest('.land-object'); if (placed && !drag) { selectedId = placed.dataset.objectId; renderScene(); } const swatch=event.target.closest('[data-color]'); if(swatch) changeSelected('color',swatch.dataset.color); });
  document.addEventListener('dragstart', (event) => { const item = event.target.closest('[data-model]'); if (item) event.dataTransfer.setData('text/plain', item.dataset.model); });
  $('#land-canvas').addEventListener('dragover', (event) => event.preventDefault()); $('#land-canvas').addEventListener('drop', (event) => { event.preventDefault(); const point = pointOnCanvas(event); addObject(event.dataTransfer.getData('text/plain'), point.x, point.y); });
  $('#land-canvas').addEventListener('pointerdown', (event) => { const element = event.target.closest('.land-object'); if (!element) { selectedId = null; renderScene(); return; } event.preventDefault(); selectedId = element.dataset.objectId; document.querySelectorAll('.land-object').forEach((item) => item.classList.toggle('selected', item === element)); const object = selected(); const point = pointOnCanvas(event); drag = { resize:event.target.classList.contains('resize-handle'), start:point, origin:{ x:object.x, y:object.y, scale:object.scale } }; element.setPointerCapture(event.pointerId); renderInspector(); });
  $('#land-canvas').addEventListener('pointermove', (event) => { if (!drag) return; const object = selected(); if (!object) return; const point = pointOnCanvas(event); if (drag.resize) object.scale = Math.max(.4, Math.min(2.4, drag.origin.scale + (point.x-drag.start.x)/24)); else { object.x = Math.max(2, Math.min(98, drag.origin.x + point.x-drag.start.x)); object.y = Math.max(2, Math.min(98, drag.origin.y + point.y-drag.start.y)); } const element = document.querySelector(`[data-object-id="${object.id}"]`); element.style.left=`${object.x}%`; element.style.top=`${object.y}%`; element.style.setProperty('--scale',object.scale); renderInspector(); });
  const endDrag = () => { if (drag) { drag = null; markChanged(); renderScene(); } }; $('#land-canvas').addEventListener('pointerup', endDrag); $('#land-canvas').addEventListener('pointercancel', endDrag);
  document.querySelectorAll('[data-library-filter]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-library-filter]').forEach((item) => item.classList.toggle('active', item === button)); renderLibrary(button.dataset.libraryFilter); }));
  $('#rotation-control').addEventListener('input', (event) => changeSelected('rotation', Number(event.target.value))); $('#scale-control').addEventListener('input', (event) => changeSelected('scale', Number(event.target.value)/100)); $('#object-color').addEventListener('input',(event)=>changeSelected('color',event.target.value)); $('#object-behavior').addEventListener('change',(event)=>changeSelected('behavior',event.target.value));
  document.querySelectorAll('[data-rotate]').forEach((button) => button.addEventListener('click', () => { const object = selected(); if (object) changeSelected('rotation', (object.rotation + Number(button.dataset.rotate) + 360) % 360); }));
  $('#reset-scale').addEventListener('click', () => changeSelected('scale', 1)); $('#position-x').addEventListener('change', (event) => changeSelected('x', Math.max(2,Math.min(98,Number(event.target.value))))); $('#position-y').addEventListener('change', (event) => changeSelected('y', Math.max(2,Math.min(98,Number(event.target.value)))));
  $('#remove-object').addEventListener('click', () => { scene.objects = scene.objects.filter((object) => object.id !== selectedId); selectedId = null; markChanged(); renderScene(); showToast('Object removed from map'); }); $('#duplicate-object').addEventListener('click', () => { const object = selected(); if (object) { const copy = {...object,id:uid(),x:Math.min(95,object.x+4),y:Math.min(95,object.y+4)}; scene.objects.push(copy); selectedId=copy.id; markChanged(); renderScene(); } });
  $('#layout-select').addEventListener('change', (event) => { updateLayout(event.target.value); markChanged(); }); $('#scene-name').addEventListener('input', (event) => { scene.name = event.target.value; markChanged(); }); $('#save-scene').addEventListener('click', () => persist(`“${scene.name || 'Untitled environment'}” saved with ${scene.objects.length} objects`));
  $('#play-scene').addEventListener('click', () => { scene.id = scene.id && scene.id !== 'active' ? scene.id : `builder-${uid()}`; scene.gameplay = { multiplayer:true, enemies:true, weapons:true, pickups:true, customRoles:true }; persist(`Opening “${scene.name || 'Untitled environment'}” as a playable multiplayer map`); location.href = `model-explorer.html?environment=${encodeURIComponent(scene.id)}&autoplay=1`; });
  $('#clear-scene').addEventListener('click', () => { if (!scene.objects.length || confirm('Start a new map? Your saved scene will remain available until you save again.')) { scene = { id:uid(), name:'Untitled environment', layout:$('#layout-select').value, objects:[] }; selectedId=null; $('#scene-name').value=scene.name; updateLayout(scene.layout); renderScene(); showToast('New map ready'); } });
  $('#land-canvas').addEventListener('keydown', (event) => { const object=selected(); if (!object) return; const moves={ArrowLeft:['x',-1],ArrowRight:['x',1],ArrowUp:['y',-1],ArrowDown:['y',1]}; if (moves[event.key]) { event.preventDefault(); const [key,amount]=moves[event.key]; object[key]=Math.max(2,Math.min(98,object[key]+amount)); markChanged(); renderScene(); } if ((event.key==='Delete'||event.key==='Backspace') && !event.target.matches('input')) $('#remove-object').click(); });
  $('#icon-picker').innerHTML=icons.map((icon,index)=>`<button type="button" data-icon="${icon}"${index===0?' aria-current="true"':''}>${icon}</button>`).join('');
  function updateMakerPreview(){ $('#maker-preview-icon').textContent=chosenIcon; $('#maker-preview-name').textContent=$('#custom-item-name').value||'Untitled item'; $('#maker-preview').style.setProperty('--item-color',$('#custom-item-color').value); }
  $('#open-item-maker').addEventListener('click',()=>{ updateMakerPreview(); $('#item-maker').showModal(); }); $('#icon-picker').addEventListener('click',(event)=>{ const button=event.target.closest('[data-icon]'); if(!button)return; chosenIcon=button.dataset.icon; $('#icon-picker').querySelectorAll('button').forEach(item=>item.setAttribute('aria-current',item===button?'true':'false')); updateMakerPreview(); }); $('#custom-item-name').addEventListener('input',updateMakerPreview); $('#custom-item-color').addEventListener('input',updateMakerPreview);
  $('#item-maker-form').addEventListener('submit',(event)=>{ if(event.submitter?.value==='cancel') return; event.preventDefault(); const name=$('#custom-item-name').value.trim(); if(!name)return; const model={id:`custom-${uid()}`,name,type:$('#custom-item-type').value,size:72,icon:chosenIcon,color:$('#custom-item-color').value,behavior:$('#custom-item-behavior').value,custom:true}; customModels.push(model); localStorage.setItem(CUSTOM_KEY,JSON.stringify(customModels)); activeFilter='all'; document.querySelectorAll('[data-library-filter]').forEach((item)=>item.classList.toggle('active',item.dataset.libraryFilter==='all')); renderLibrary(); addObject(model.id); $('#item-maker').close(); showToast(`${name} added to your custom library`); });
  const requested = new URLSearchParams(location.search).get('layout'); const saved = readJson(STORAGE_KEY, null); if (saved && !requested && Array.isArray(saved.objects)) scene = saved; if (requested && layouts[requested]) scene.layout = requested; scene.objects=scene.objects.filter(object=>modelFor(object.modelId)).map(object=>({...object,color:object.color||modelFor(object.modelId).color||colors[0],behavior:object.behavior||modelFor(object.modelId).behavior||'decor'})); importBuildTray(); $('#scene-name').value = scene.name || 'Untitled environment'; updateLayout(scene.layout); renderScene();
}());
