(function(){
'use strict';
const bolt='<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M36 2 12 36h17l-3 26 26-38H35z"/></svg>';
const hamburger='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18"/></svg>';
const icons={models:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v14H4zM8 9h8M8 13h5"/></svg>',market:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9h16l-1-5H5zM6 9v11h12V9M9 20v-6h6v6"/></svg>',world:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6l5-2 8 3 5-2v13l-5 2-8-3-5 2zM8 4v13M16 7v13"/></svg>',members:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3a4 4 0 110 8 4 4 0 010-8zM5 21c0-5 2-8 7-8s7 3 7 8"/></svg>',checkout:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 4h2l2 11h10l3-8H6M9 20h.01M17 20h.01"/></svg>',token:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2v20M17 6.5c-1-1-2.5-1.5-5-1.5-3 0-5 1.2-5 3s2 3 5 3 5 1.2 5 3-2 3-5 3c-2.5 0-4-.5-5-1.5"/></svg>',backpack:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 8V6a4 4 0 018 0v2M6 8h12a2 2 0 012 2v10H4V10a2 2 0 012-2zM8 12v2M16 12v2M8 17h8"/></svg>',support:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v12H9l-5 4zM8 9h8M8 13h5"/></svg>'};
const tile=(href,label,icon,extra='')=>`<a class="mzk-header-tile" href="${href}" ${extra} aria-label="${label}">${icons[icon]}<span>${label}</span></a>`;
function wallet(){return String(window.MZKWallet?.connectedAddress?.()||window.MZKWallet?.walletId?.()||localStorage.getItem('muzikazBottleMemberEmail')||'').trim().toLowerCase()}
function name(){return window.MZKWallet?.profile?.()?.username||localStorage.getItem('muzikazBottleMemberEmail')||'Member'}
function safe(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initials(v){return String(v||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function install(){
 const prior=document.querySelector('header.site-header, header.masthead');
 const header=document.createElement('header'); header.className='mzk-global-bar';
 header.innerHTML=`<a class="mzk-global-logo" href="index.html" aria-label="MUZIKAZ home">${bolt}<span>MUZIKAZ</span></a><nav class="mzk-global-nav" aria-label="Main navigation">${tile('index.html#models','Models','models')}${tile('model-market.html','Market','market')}${tile('model-explorer.html','World','world')}${tile('members.html','Members','members')}${tile('checkout.html','Checkout','checkout')}${tile('buy-mzk.html','Buy MZK','token')}</nav><div class="mzk-mobile-actions">${tile('checkout.html','Checkout','checkout')}${tile('buy-mzk.html','Buy MZK','token')}${tile('members.html#owned-collection','Backpack','backpack')}</div><button class="mzk-support-action" type="button" aria-label="Open support chat">${icons.support}<span>Support</span></button><button class="mzk-menu-toggle" type="button" aria-expanded="false" aria-controls="mzk-member-drawer">${hamburger}<span>Menu</span></button>`;
 if(prior){prior.querySelectorAll('.mzk-backpack-dock,.mzk-mobile-header').forEach(control=>header.appendChild(control));prior.replaceWith(header)} else document.body.prepend(header);
 const backdrop=document.createElement('div');backdrop.className='mzk-drawer-backdrop';backdrop.hidden=true;
 const drawer=document.createElement('aside');drawer.id='mzk-member-drawer';drawer.className='mzk-member-drawer';drawer.hidden=true;drawer.setAttribute('aria-label','Menu and member messages');
 drawer.innerHTML=`<div class="mzk-drawer-head"><div><small>MUZIKAZ NETWORK</small><h2>Menu & members</h2></div><button class="mzk-drawer-close" aria-label="Close menu">×</button></div><nav class="mzk-drawer-links"><a href="index.html">Home</a><a href="model-market.html">Market</a><a href="model-explorer.html">Game</a><a href="members.html">Member hub</a><a href="checkout.html">Checkout</a><a href="admin.html">Admin</a></nav><p class="mzk-member-status" role="status">Connect a member wallet to open live messages.</p><div class="mzk-member-list" aria-label="Member profiles"></div><section class="mzk-member-chat" hidden><div class="mzk-chat-title">Choose a member</div><ol class="mzk-chat-log" aria-live="polite"></ol><form class="mzk-chat-form"><label style="position:absolute;left:-9999px" for="mzk-chat-input">Message</label><input id="mzk-chat-input" maxlength="500" placeholder="Message this member…" required><button>Send</button></form></section>`;
 document.body.append(backdrop,drawer);
 const toggle=header.querySelector('.mzk-menu-toggle'),close=()=>{drawer.hidden=backdrop.hidden=true;toggle.setAttribute('aria-expanded','false')},open=()=>{drawer.hidden=backdrop.hidden=false;toggle.setAttribute('aria-expanded','true');loadMembers()};
 toggle.onclick=()=>drawer.hidden?open():close();drawer.querySelector('.mzk-drawer-close').onclick=close;backdrop.onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
 header.querySelector('.mzk-support-action').onclick=()=>document.querySelector('.support-chat-toggle')?.click();
 let peer='',socket=null,messages=[];
 const status=drawer.querySelector('.mzk-member-status'),list=drawer.querySelector('.mzk-member-list'),chat=drawer.querySelector('.mzk-member-chat'),log=drawer.querySelector('.mzk-chat-log'),title=drawer.querySelector('.mzk-chat-title');
 const render=()=>{const me=wallet();const thread=messages.filter(m=>(m.from===me&&m.to===peer)||(m.from===peer&&m.to===me));log.innerHTML=thread.map(m=>`<li class="${m.from===me?'is-mine':''}">${safe(m.text)}<small>${m.from===me?'You':safe(m.from)} · ${new Date(m.createdAt).toLocaleString()}</small></li>`).join('')||'<li>No messages yet. Say hello.</li>';log.scrollTop=log.scrollHeight};
 function connect(){const me=wallet();if(!me||me.startsWith('guest-')){status.textContent='Connect a member wallet to start messaging.';return}if(socket&&socket.readyState<2)return;const url=new URL('/ws/members',location.href);url.protocol=url.protocol==='https:'?'wss:':'ws:';url.searchParams.set('userId',me);url.searchParams.set('name',name());socket=new WebSocket(url);socket.onopen=()=>status.textContent='Live member chat connected.';socket.onclose=()=>{status.textContent='Member chat reconnecting…';socket=null;setTimeout(connect,1800)};socket.onmessage=e=>{const data=JSON.parse(e.data);if(data.type==='history')messages=data.messages||[];if(data.type==='message')messages.push(data.message);if(data.type==='error')status.textContent=data.message;render()}}
 async function loadMembers(){connect();try{const response=await fetch('/api/market/members',{headers:{Accept:'application/json'}}),payload=await response.json();if(!response.ok)throw new Error(payload.message);const me=wallet(),members=(payload.data||[]).filter(m=>m.walletId!==me);list.innerHTML=members.map(m=>`<button class="mzk-member-card" data-member="${safe(m.walletId)}"><span class="mzk-member-avatar">${safe(initials(m.displayName))}</span><span><b>${safe(m.displayName)}</b><small>${m.itemCount} Backpack item${m.itemCount===1?'':'s'}</small></span><span aria-hidden="true">›</span></button>`).join('')||'<p class="mzk-member-status">No other member profiles are available yet.</p>';list.querySelectorAll('[data-member]').forEach(button=>button.onclick=()=>{peer=button.dataset.member;list.querySelectorAll('button').forEach(b=>b.classList.toggle('is-active',b===button));title.textContent=`Chat with ${button.querySelector('b').textContent}`;chat.hidden=false;render();drawer.querySelector('input').focus()})}catch(e){status.textContent=e.message||'Member list is unavailable.'}}
 drawer.querySelector('form').onsubmit=e=>{e.preventDefault();const input=e.currentTarget.querySelector('input');if(!peer)return;if(!socket||socket.readyState!==WebSocket.OPEN){status.textContent='Live chat is still connecting.';return}socket.send(JSON.stringify({to:peer,message:input.value}));input.value=''};
 window.addEventListener('mzk:wallet-connection-changed',()=>{socket?.close();socket=null;loadMembers()});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
}());
