(function(){
'use strict';
const bolt='<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M36 2 12 36h17l-3 26 26-38H35z"/></svg>';
const hamburger='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18"/></svg>';
function wallet(){return String(window.MZKWallet?.connectedAddress?.()||window.MZKWallet?.walletId?.()||localStorage.getItem('muzikazBottleMemberEmail')||'').trim().toLowerCase()}
function name(){return window.MZKWallet?.profile?.()?.username||localStorage.getItem('muzikazBottleMemberEmail')||'Member'}
function safe(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initials(v){return String(v||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function install(){
 const prior=document.querySelector('header.site-header, header.masthead');
 const header=document.createElement('header'); header.className='mzk-global-bar';
 header.innerHTML=`<a class="mzk-global-logo" href="index.html" aria-label="MUZIKAZ home">${bolt}<span>MUZIKAZ</span></a><nav class="mzk-global-nav" aria-label="Main navigation"><a href="index.html#models">Models</a><a href="model-market.html">Market</a><a href="model-explorer.html">World</a><a href="members.html">Members</a></nav><button class="mzk-menu-toggle" type="button" aria-expanded="false" aria-controls="mzk-member-drawer">${hamburger}<span>Menu</span></button>`;
 if(prior) prior.replaceWith(header); else document.body.prepend(header);
 const backdrop=document.createElement('div');backdrop.className='mzk-drawer-backdrop';backdrop.hidden=true;
 const drawer=document.createElement('aside');drawer.id='mzk-member-drawer';drawer.className='mzk-member-drawer';drawer.hidden=true;drawer.setAttribute('aria-label','Menu and member messages');
 drawer.innerHTML=`<div class="mzk-drawer-head"><div><small>MUZIKAZ NETWORK</small><h2>Menu & members</h2></div><button class="mzk-drawer-close" aria-label="Close menu">×</button></div><nav class="mzk-drawer-links"><a href="index.html">Home</a><a href="model-market.html">Market</a><a href="model-explorer.html">Game</a><a href="members.html">Member hub</a><a href="checkout.html">Checkout</a></nav><p class="mzk-member-status" role="status">Connect a member wallet to open live messages.</p><div class="mzk-member-list" aria-label="Member profiles"></div><section class="mzk-member-chat" hidden><div class="mzk-chat-title">Choose a member</div><ol class="mzk-chat-log" aria-live="polite"></ol><form class="mzk-chat-form"><label style="position:absolute;left:-9999px" for="mzk-chat-input">Message</label><input id="mzk-chat-input" maxlength="500" placeholder="Message this member…" required><button>Send</button></form></section>`;
 document.body.append(backdrop,drawer);
 const toggle=header.querySelector('.mzk-menu-toggle'),close=()=>{drawer.hidden=backdrop.hidden=true;toggle.setAttribute('aria-expanded','false')},open=()=>{drawer.hidden=backdrop.hidden=false;toggle.setAttribute('aria-expanded','true');loadMembers()};
 toggle.onclick=()=>drawer.hidden?open():close();drawer.querySelector('.mzk-drawer-close').onclick=close;backdrop.onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
 let peer='',socket=null,messages=[];
 const status=drawer.querySelector('.mzk-member-status'),list=drawer.querySelector('.mzk-member-list'),chat=drawer.querySelector('.mzk-member-chat'),log=drawer.querySelector('.mzk-chat-log'),title=drawer.querySelector('.mzk-chat-title');
 const render=()=>{const me=wallet();const thread=messages.filter(m=>(m.from===me&&m.to===peer)||(m.from===peer&&m.to===me));log.innerHTML=thread.map(m=>`<li class="${m.from===me?'is-mine':''}">${safe(m.text)}<small>${m.from===me?'You':safe(m.from)} · ${new Date(m.createdAt).toLocaleString()}</small></li>`).join('')||'<li>No messages yet. Say hello.</li>';log.scrollTop=log.scrollHeight};
 function connect(){const me=wallet();if(!me||me.startsWith('guest-')){status.textContent='Connect a member wallet to start messaging.';return}if(socket&&socket.readyState<2)return;const url=new URL('/ws/members',location.href);url.protocol=url.protocol==='https:'?'wss:':'ws:';url.searchParams.set('userId',me);url.searchParams.set('name',name());socket=new WebSocket(url);socket.onopen=()=>status.textContent='Live member chat connected.';socket.onclose=()=>{status.textContent='Member chat reconnecting…';socket=null;setTimeout(connect,1800)};socket.onmessage=e=>{const data=JSON.parse(e.data);if(data.type==='history')messages=data.messages||[];if(data.type==='message')messages.push(data.message);if(data.type==='error')status.textContent=data.message;render()}}
 async function loadMembers(){connect();try{const response=await fetch('/api/market/members',{headers:{Accept:'application/json'}}),payload=await response.json();if(!response.ok)throw new Error(payload.message);const me=wallet(),members=(payload.data||[]).filter(m=>m.walletId!==me);list.innerHTML=members.map(m=>`<button class="mzk-member-card" data-member="${safe(m.walletId)}"><span class="mzk-member-avatar">${safe(initials(m.displayName))}</span><span><b>${safe(m.displayName)}</b><small>${m.itemCount} Backpack item${m.itemCount===1?'':'s'}</small></span><span aria-hidden="true">›</span></button>`).join('')||'<p class="mzk-member-status">No other member profiles are available yet.</p>';list.querySelectorAll('[data-member]').forEach(button=>button.onclick=()=>{peer=button.dataset.member;list.querySelectorAll('button').forEach(b=>b.classList.toggle('is-active',b===button));title.textContent=`Chat with ${button.querySelector('b').textContent}`;chat.hidden=false;render();drawer.querySelector('input').focus()})}catch(e){status.textContent=e.message||'Member list is unavailable.'}}
 drawer.querySelector('form').onsubmit=e=>{e.preventDefault();const input=e.currentTarget.querySelector('input');if(!peer)return;if(!socket||socket.readyState!==WebSocket.OPEN){status.textContent='Live chat is still connecting.';return}socket.send(JSON.stringify({to:peer,message:input.value}));input.value=''};
 window.addEventListener('mzk:wallet-connection-changed',()=>{socket?.close();socket=null;loadMembers()});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
}());
