(function(){
const A=window.Voice3Audio,$=s=>document.querySelector(s),px=s=>s*Number($('#zoom').value);let audioCtx,playing=false,startCtx=0,pos=0,nodes=[],selected=null,clipBoard=null,history=[],future=[];
const project={version:'voice3-project-v1',id:A.uid('project'),title:'Untitled Voice3 Mix',createdAt:new Date().toISOString(),modifiedAt:new Date().toISOString(),bpm:104,timeSignature:[4,4],loop:{enabled:false,start:0,end:30},master:{volume:0.9,bass:0,mid:0,treble:0,compressor:true,limiter:true},tracks:[]};
const defaults=[['voice','Voice','#ffda3a'],['bass','Bass','#ff5a19'],['drums','Drums','#9cff00'],['music','Music','#24d8ff'],['effects','Effects','#f05cff'],['nft','NFT Audio','#b8ffef']];
function track(id,name,color){return{id,name,color,mute:false,solo:false,volume:.9,pan:0,bass:0,mid:0,treble:0,highPass:20,lowPass:20000,reverb:0,delay:0,collapsed:false,locked:false,clips:[]}}
defaults.forEach(d=>project.tracks.push(track(...d)));
function snapshot(){history.push(JSON.stringify(project)); if(history.length>40)history.shift(); future=[]; autosave();}
const deb=fn=>{let t;return()=>{clearTimeout(t);t=setTimeout(fn,500)}}; const autosave=deb(()=>A.put({...project,modifiedAt:new Date().toISOString()},A.PROJECTS));
function duration(){return Math.max(30,...project.tracks.flatMap(t=>t.clips.map(c=>c.start+c.duration)))}
function render(){project.bpm=Number($('#bpm').value)||104; $('#readout').value=`${fmt(pos)} / ${fmt(duration())}`; $('#token-status').textContent='Reward tokens: …'; A.balance().then(b=>$('#token-status').textContent=`Reward tokens: ${b} · dev local wallet`); renderFilters(); renderLib(); renderTracks(); renderInspector(); renderRuler();}
function fmt(s){const m=Math.floor(s/60),sec=Math.floor(s%60),ms=Math.floor((s%1)*1000);return`${m}:${String(sec).padStart(2,'0')}.${String(ms).padStart(3,'0')}`}
function renderRuler(){const d=duration(),step=5; $('#time-ruler').innerHTML=Array.from({length:Math.ceil(d/step)+1},(_,i)=>`<span style="left:${px(i*step)}px">${fmt(i*step).slice(0,4)}</span>`).join('')+`<b class="playhead" style="left:${px(pos)}px"></b>`}
async function renderLib(filter=window.libFilter||'all'){const items=await A.all(); const list=$('#library-list'); list.innerHTML=items.filter(i=>filter==='all'||i.category===filter||i.sourceType===filter).map(card).join('')||'<p class="empty-state">Record or drop audio to build your reusable library.</p>'}
function card(i){return`<article class="audio-card" draggable="true" data-audio="${i.id}"><strong>${i.displayName}</strong><small>${i.category} · ${fmt(i.duration||0)}</small><div class="wave">${(i.waveformData||[]).slice(0,36).map(v=>`<i style="height:${10+v*28}px"></i>`).join('')}</div><button data-act="preview">Preview</button><button data-act="add">Add</button><button data-act="download">Download</button><button data-act="dup">Duplicate</button><button data-act="del">Delete</button></article>`}
function renderFilters(){const f=$('#filters'); if(f.childElementCount)return; ['all','voice','upload','bass','beat','loop','effect','nft','mix'].forEach(x=>{const b=document.createElement('button');b.textContent=x==='all'?'All Sounds':x;b.onclick=()=>{window.libFilter=x;renderLib(x)};f.append(b)})}
async function builtins(){const box=$('#builtins'); box.innerHTML=''; for(const [name,cat,freq,type] of [['Sub Bass','bass',55,'sine'],['Kick','beat',75,'sine'],['Snare','beat',180,'square'],['Hi-hat','effect',9000,'square'],['Rise FX','effect',440,'saw'],['Ambient Pad','loop',220,'sine']]){const blob=A.makeToneBlob(freq,cat==='loop'?2:1,type); const item=await A.itemFromBlob(blob,{displayName:name,sourceType:'built-in',category:cat}); box.insertAdjacentHTML('beforeend',card(item));}}
function renderTracks(){const el=$('#tracks'); el.style.minWidth=px(duration()+4)+'px'; el.innerHTML=project.tracks.map(t=>`<article class="pro-track ${t.collapsed?'collapsed':''}" data-track="${t.id}"><header><input value="${t.name}" aria-label="Track name"><button data-t="mute">${t.mute?'Unmute':'Mute'}</button><button data-t="solo">Solo</button><label>Vol<input data-t="volume" type="range" min="0" max="1.5" step=".01" value="${t.volume}"></label><label>Pan<input data-t="pan" type="range" min="-1" max="1" step=".01" value="${t.pan}"></label><label>Bass<input data-t="bass" type="range" min="-18" max="18" value="${t.bass}"></label><button data-t="dup">Duplicate</button><button data-t="delete">Delete</button></header><div class="clip-lane">${t.clips.map(c=>clip(t,c)).join('')}</div></article>`).join('')}
function clip(t,c){return`<div class="clip ${selected===c.id?'selected':''}" tabindex="0" draggable="true" data-clip="${c.id}" style="left:${px(c.start)}px;width:${px(c.duration)}px;background:${t.color}"><b>${c.name}</b><small>${fmt(c.start)} · ${fmt(c.duration)} · x${c.rate}</small><span class="fade" style="width:${Math.min(100,c.fadeIn*20)}%"></span><i class="resize left"></i><i class="resize right"></i></div>`}
function renderInspector(){const c=findClip(selected); $('#inspector-empty').hidden=!!c; $('#clip-form').hidden=!c; if(c){for(const k of ['start','duration','trimStart','trimEnd','fadeIn','fadeOut','gain','rate']) $('#clip-form')[k].value=c[k]??0;} $('#master-form').volume.value=project.master.volume; ['bass','mid','treble'].forEach(k=>$('#master-form')[k].value=project.master[k]);}
function findClip(id){for(const t of project.tracks){const c=t.clips.find(x=>x.id===id); if(c)return c} return null} function findTrack(id){return project.tracks.find(t=>t.id===id)}
async function addClip(item,trackId='voice',start=pos){snapshot(); const t=findTrack(trackId)||project.tracks[0]; t.clips.push({id:A.uid('clip'),audioId:item.id,name:item.displayName,start,duration:item.duration||1,trimStart:item.trimStart||0,trimEnd:item.trimEnd||item.duration,fadeIn:0,fadeOut:0,gain:1,rate:1,reverse:false,loop:false,effects:item.effectSettings||{}}); A.dispatch(t.id==='bass'||item.category==='bass'?'bass-added':'clip-added',{audioId:item.id,trackId:t.id,start}); render();}
async function importFiles(files){let done=0; for(const file of files){try{const item=await A.itemFromBlob(file,{displayName:file.name,originalFilename:file.name,sourceType:'upload',category:'upload'}); A.dispatch('audio-uploaded',{audioId:item.id,name:item.displayName});}catch(e){alert(`${file.name}: ${e.message}`)} $('#import-progress').value=++done/files.length*100;} render();}
function stop(){nodes.forEach(n=>{try{n.stop?.();n.disconnect?.()}catch{}});nodes=[];playing=false;}
async function play(){if(playing){pos=audioCtx.currentTime-startCtx; stop(); render(); return;} stop(); audioCtx=new (window.AudioContext||window.webkitAudioContext)(); await audioCtx.resume(); playing=true; startCtx=audioCtx.currentTime-pos; const solo=project.tracks.filter(t=>t.solo); for(const t of project.tracks){if(t.mute||(solo.length&&!t.solo))continue; for(const c of t.clips){const item=await A.get(c.audioId); if(!item?.blob)continue; const buf=await audioCtx.decodeAudioData(await item.blob.arrayBuffer()); const when=Math.max(0,c.start-pos); const offset=Math.max(c.trimStart,pos-c.start+c.trimStart); if(offset>=buf.duration)continue; const src=audioCtx.createBufferSource(), gain=audioCtx.createGain(), pan=audioCtx.createStereoPanner(), bass=audioCtx.createBiquadFilter(), mid=audioCtx.createBiquadFilter(), treble=audioCtx.createBiquadFilter(); src.buffer=buf; src.playbackRate.value=c.rate; bass.type='lowshelf';bass.frequency.value=160;bass.gain.value=t.bass; mid.type='peaking';mid.frequency.value=1200;mid.gain.value=t.mid; treble.type='highshelf';treble.frequency.value=4200;treble.gain.value=t.treble; gain.gain.value=c.gain*t.volume; pan.pan.value=t.pan; src.connect(gain).connect(pan).connect(bass).connect(mid).connect(treble).connect(audioCtx.destination); const dur=Math.min(c.duration-(offset-c.trimStart),buf.duration-offset); gain.gain.setValueAtTime(.0001,audioCtx.currentTime+when); gain.gain.linearRampToValueAtTime(c.gain*t.volume,audioCtx.currentTime+when+c.fadeIn); gain.gain.setValueAtTime(c.gain*t.volume,audioCtx.currentTime+when+Math.max(0,dur-c.fadeOut)); gain.gain.linearRampToValueAtTime(.0001,audioCtx.currentTime+when+dur); src.start(audioCtx.currentTime+when,offset,dur); nodes.push(src,gain,pan,bass,mid,treble);}} tick();}
function tick(){if(!playing)return; pos=audioCtx.currentTime-startCtx; if(pos>=duration()){stop();pos=0} renderRuler(); $('#readout').value=`${fmt(pos)} / ${fmt(duration())}`; requestAnimationFrame(tick)}
async function exportWav(){stop(); const sr=44100,len=Math.ceil(duration()*sr),mix=new Float32Array(len); for(const t of project.tracks){for(const c of t.clips){const item=await A.get(c.audioId); if(!item?.blob)continue; const ctx=new OfflineAudioContext(1,Math.ceil((c.trimEnd-c.trimStart)*sr),sr); const b=await ctx.decodeAudioData(await item.blob.arrayBuffer()); const data=b.getChannelData(0); const start=Math.floor(c.start*sr), off=Math.floor(c.trimStart*sr), clen=Math.min(Math.floor(c.duration*sr),data.length-off); for(let i=0;i<clen&&start+i<mix.length;i++){const fade=Math.min(1,i/Math.max(1,c.fadeIn*sr),(clen-i)/Math.max(1,c.fadeOut*sr)); mix[start+i]+=data[off+i]*(c.gain||1)*t.volume*fade;}}} const blob=A.wavBlob([mix.map(v=>Math.max(-1,Math.min(1,v*project.master.volume)))],sr); const item=await A.itemFromBlob(blob,{displayName:`${project.title} export.wav`,sourceType:'export',category:'mix'}); A.dispatch('mix-exported',{audioId:item.id,duration:duration()}); localStorage.setItem('voice3.mintAudioId',item.id); render(); alert(`Exported ${item.displayName} to Audio Library.`)}
function downloadJSON(){const blob=new Blob([JSON.stringify({...project,modifiedAt:new Date().toISOString()},null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=A.sanitizeName(project.title)+'.voice3.json'; a.click(); URL.revokeObjectURL(a.href); A.dispatch('mix-saved',{projectId:project.id});}
function bind(){document.addEventListener('dragstart',e=>{const a=e.target.closest('[data-audio]'),c=e.target.closest('[data-clip]'); if(a)e.dataTransfer.setData('audio-id',a.dataset.audio); if(c){selected=c.dataset.clip;e.dataTransfer.setData('clip-id',selected)}}); $('#tracks').ondragover=e=>{if(e.target.closest('.clip-lane'))e.preventDefault()}; $('#tracks').ondrop=async e=>{const lane=e.target.closest('.clip-lane'); if(!lane)return; e.preventDefault(); const tid=lane.closest('[data-track]').dataset.track, aid=e.dataTransfer.getData('audio-id'), cid=e.dataTransfer.getData('clip-id'); const st=Math.max(0,(e.offsetX||0)/Number($('#zoom').value)); if(aid)addClip(await A.get(aid),tid,st); if(cid){snapshot(); const c=findClip(cid); project.tracks.forEach(t=>t.clips=t.clips.filter(x=>x.id!==cid)); findTrack(tid).clips.push(c); c.start=st; A.dispatch('clip-moved',{clipId:cid,trackId:tid,start:st}); render();}};
$('#library-list').onclick=$('#builtins').onclick=async e=>{const card=e.target.closest('[data-audio]'); if(!card)return; const item=await A.get(card.dataset.audio); const act=e.target.dataset.act; if(act==='preview') new Audio(A.url(item)).play(); if(act==='add') addClip(item); if(act==='download'){const a=document.createElement('a');a.href=A.url(item);a.download=item.displayName;a.click()} if(act==='dup'){await A.itemFromBlob(item.blob,{...item,id:null,displayName:item.displayName+' copy'});render()} if(act==='del'&&confirm('Delete audio item?')){await A.del(item.id);render()}};
$('#drop-zone').ondragover=e=>e.preventDefault(); $('#drop-zone').ondrop=e=>{e.preventDefault(); importFiles(e.dataTransfer.files)}; $('#file-input').onchange=e=>importFiles(e.target.files); $('#play').onclick=play; $('#stop').onclick=()=>{stop();pos=0;render()}; $('#export-wav').onclick=exportWav; $('#download-project').onclick=downloadJSON; $('#save-project').onclick=()=>{A.put(project,A.PROJECTS);A.dispatch('mix-saved',{projectId:project.id});alert('Session saved locally.')}; $('#add-track').onclick=()=>{snapshot();project.tracks.push(track(A.uid('track'),'New Track','#ffda3a'));render()}; $('#split').onclick=()=>{const c=findClip(selected); if(!c||pos<=c.start||pos>=c.start+c.duration)return; snapshot(); const d=c.start+c.duration-pos; c.duration=pos-c.start; findTrack(project.tracks.find(t=>t.clips.includes(c)).id).clips.push({...c,id:A.uid('clip'),start:pos,duration:d,trimStart:c.trimStart+c.duration}); A.dispatch('clip-trimmed',{clipId:c.id});render()}; $('#duplicate').onclick=()=>{const c=findClip(selected); if(!c)return; snapshot(); project.tracks.find(t=>t.clips.includes(c)).clips.push({...c,id:A.uid('clip'),start:c.start+c.duration}); render()}; $('#delete').onclick=()=>{snapshot();project.tracks.forEach(t=>t.clips=t.clips.filter(c=>c.id!==selected));selected=null;render()}; $('#undo').onclick=()=>{if(!history.length)return;future.push(JSON.stringify(project));Object.assign(project,JSON.parse(history.pop()));render()}; $('#redo').onclick=()=>{if(!future.length)return;history.push(JSON.stringify(project));Object.assign(project,JSON.parse(future.pop()));render()}; $('#clip-form').oninput=e=>{const c=findClip(selected); if(!c)return; c[e.target.name]=Number(e.target.value); A.dispatch(e.target.name.startsWith('fade')?'effect-applied':'clip-trimmed',{clipId:c.id,field:e.target.name}); autosave(); renderTracks();}; $('#master-form').oninput=e=>{project.master[e.target.name]=Number(e.target.value);autosave()}; $('#tracks').onclick=e=>{const c=e.target.closest('[data-clip]'); if(c){selected=c.dataset.clip; renderInspector(); renderTracks()}}; $('#mint-mix').onclick=()=>{location.href='checkout.html?mintAudioId='+(localStorage.getItem('voice3.mintAudioId')||'')}; document.onkeydown=e=>{if(/input|textarea|select/i.test(e.target.tagName))return; if(e.code==='Space'){e.preventDefault();play()} if(e.key==='Delete'||e.key==='Backspace')$('#delete').click(); if((e.ctrlKey||e.metaKey)&&e.key==='z')$('#undo').click(); if((e.ctrlKey||e.metaKey)&&e.key==='d')$('#duplicate').click(); if(e.key.toLowerCase()==='s')$('#split').click();}; window.addEventListener('voice3:add-to-mixer',e=>addClip(e.detail.item,'voice',pos));}
A.openDb().then(()=>{render(); builtins(); bind(); A.get(localStorage.getItem('voice3.pendingMixerAudio')).then(i=>i&&addClip(i,'voice',pos));});
})();
